##########################################################
### Home Assistant Configuration                      ####
##########################################################

homeassistant:
  # Name of the location where Home Assistant is running
  name: 'Otter Den'

  # Location required to calculate the time the sun rises and sets
  latitude: !secret ha_latitude
  longitude: !secret ha_longitude

  # Impacts weather/sunrise data (altitude above sea level)
  elevation: !secret ha_elevation

  # 'metric' for Metric, 'imperial' for Imperial
  unit_system: imperial

  # Pick yours from here:
  # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Detroit

  # Customizations
  customize: !include_dir_merge_named customizations/

# HA Website
http:
  api_password: !secret ha_password
  base_url: !secret ha_url
  # server_port: 8123

# Discover some devices automatically
discovery:

# Enables the frontend
frontend:

# Enables support for tracking state changes over time.
history:

# Checks for available updates
updater:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Allows you to issue voice commands from the frontend
conversation:

# Expose Home Assistant over Bonjour
zeroconf:

# Creates port forward mapping in router
upnp:

# Service to open URLs in the default browser
browser:

# Simulates key presses on the host machine
keyboard:

##########################################################
### SERVICES                                          ####
##########################################################

# Nest Learning Thermosat
nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

# Media Players
media_player:
  - platform: sonos
  - platform: roku
  - platform: yamaha
    name: 'Basement Receiver'
  - platform: webostv
    host: 192.168.0.9
    mac: 14:C9:13:7C:BB:FE
    name: 'Living Room TV'

# Philips Hue
light:
  platform: hue
  host: 192.168.0.16
  allow_unreachable: true

# Vera platform
vera:
  vera_controller_url: http://192.168.0.7:3480/
  exclude: [2, 3, 4, 5, 8, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 37, 41]
  lights: [15]

# Z-Wave
#zwave:
#  usb_path: /dev/zwave
#  polling_interval: 60000
#  config_path: /srv/hass/src/open-zwave-control-panel/config

# Twilio notifications
notify:
  - name: twilio
    platform: twilio_sms
    account_sid: !secret twilio_sid
    auth_token: !secret twilio_token
    from_number: !secret twilio_number

# IFTTT
ifttt:
  key: !secret ifttt_secret

# MQTT
#mqtt:
#  broker: 127.0.0.1
#  port: 1883
#  client_id: otteropolis-ha
#  username: !secret mqtt_username
#  password: !secret mqtt_password

##########################################################
### INCLUDES                                          ####
##########################################################

# Automation #
automation: !include_dir_list automation/

# Zones #
zone: !include zones.yaml

# Sensors #
sensor: !include sensors.yaml

# Switches #
switch: !include switches.yaml

# Device Tracker #
device_tracker: !include device_tracker.yaml

# Shell Commands #
shell_command: !include shell_commands.yaml

# Scripts #
script: !include scripts.yaml

# Groups #
group: !include_dir_merge_named groups/

# Weblinks #
weblink: !include weblinks.yaml
