##########################################################
### Home Assistant Configuration                      ####
##########################################################

homeassistant:
  # Name of the location where Home Assistant is running
  name: 'Otter Den'

  # Location required to calculate the time the sun rises and sets
  latitude: !secret ha_latitude
  longitude: !secret ha_longitude

  # Impacts weather/sunrise data (altitude above sea level)
  elevation: !secret ha_elevation

  # 'metric' for Metric, 'imperial' for Imperial
  unit_system: imperial

  # Pick yours from here:
  # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Detroit

  # Customizations
  customize: !include_dir_merge_named customizations/

# HA Website
http:
  api_password: !secret ha_password
  server_port: 8123

# Discover some devices automatically
discovery:

# Enables the frontend
frontend:

# Enables support for tracking state changes over time.
history:

# Checks for available updates
updater:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Allows you to issue voice commands from the frontend
conversation:

# Creates port forward mapping in router
upnp:

##########################################################
### SERVICES                                          ####
##########################################################

# Nest Learning Thermosat
nest:
  username: !secret nest_username
  password: !secret nest_password

thermostat:
  platform: nest

# Sonos
media_player:
  platform: sonos

# Twilio notifications
notify:
  platform: twilio_sms
  name: twilio
  account_sid: !secret twilio_sid
  auth_token: !secret twilio_token
  from_number: !secret twilio_number

# IFTTT
ifttt:
  key: !secret ifttt_secret

# MQTT
mqtt:
  broker: 127.0.0.1
  port: 1883
  client_id: otteropolis-ha
  username: !secret mqtt_username
  password: !secret mqtt_password

##########################################################
### INCLUDES                                          ####
##########################################################

# Automation #
automation: !include_dir_list automation/

# Zones #
zone: !include zones.yaml

# Sensors #
sensor: !include sensors.yaml

# Switches #
switch: !include switches.yaml

# Device Tracker #
device_tracker: !include device_tracker.yaml

# Shell Commands #
shell_command: !include shell_commands.yaml

# Scripts #
# script: !include scripts.yaml

# Groups #
group: !include_dir_merge_named groups/
