##########################################################
### Home Assistant Configuration                      ####
##########################################################

homeassistant:
  # Name of the location where Home Assistant is running
  name: 'Otteropolis'

  # Location required to calculate the time the sun rises and sets
  latitude: !secret ha_latitude
  longitude: !secret ha_longitude

  # Impacts weather/sunrise data (altitude above sea level)
  elevation: !secret ha_elevation

  # 'metric' for Metric, 'imperial' for Imperial
  unit_system: imperial

  # Pick yours from here:
  # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret ha_time_zone

  # Customizations
  customize: !include_dir_merge_named customize/

####################################################
### GENERAL                                     ####
####################################################

# Cloud
# https://www.home-assistant.io/components/cloud/
cloud:
  alexa:
    filter:
      exclude_domains:
        - group
        - automation
        - alert
      exclude_entities:
        - light.hgrp0000000254
        - switch.raspberry_pi
        - switch.pc
        - switch.imac

# Enables configuration UI
# https://home-assistant.io/components/config/
config:

# Allows you to issue voice commands from the frontend
# https://www.home-assistant.io/components/conversation/
conversation:

# https://www.home-assistant.io/components/device_tracker
device_tracker:
  - platform: netgear
    host: 192.168.0.1
    username: !secret netgear_username
    password: !secret netgear_password
    new_device_defaults:
      track_new_devices: False
      hide_if_away: False

# Discover some devices automatically
# https://www.home-assistant.io/components/discovery/
discovery:

# Enables the frontend
# https://www.home-assistant.io/components/frontend/
frontend:
  javascript_version: latest

# Enables support for tracking state changes over time.
# https://home-assistant.io/components/history/
history:

# HA Website
# https://home-assistant.io/components/http/
http:
  # Secrets are defined in the file secrets.yaml
  api_password: !secret ha_password
  base_url: !secret ha_url
  cors_allowed_origins:
      - https://google.com
      - https://www.home-assistant.io
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - ::1
    - 192.168.0.7
  trusted_networks:
    - 127.0.0.1
    - ::1
    - 192.168.0.0/24
    - fd00::/8
  ip_ban_enabled: true
  login_attempts_threshold: 5

# iOS
# https://www.home-assistant.io/components/ios/
ios:

# View all events in a logbook
# https://www.home-assistant.io/components/logbook/
logbook:

# Enables a map showing the location of tracked devices
# https://www.home-assistant.io/components/map/
map:

# Notifications
# https://www.home-assistant.io/components/notify.twilio_sms/
notify:
  - name: sms
    platform: twilio_sms
    from_number: !secret twilio_number

# Limit History
# https://home-assistant.io/components/recorder/
recorder:
  purge_interval: 1
  purge_keep_days: 3
  exclude:
      domains:
        - automation
        - weblink
        - updater
      entities:
        - sun.sun # Don't record sun data
        - sensor.since_last_boot
        - sensor.date
        - sensor.time

# Track the sun
# https://home-assistant.io/components/sun/
sun:

# Text to speech
tts:
  - platform: google

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  include_used_components: true

# Zeroconf/Avahi/Bonjour
# https://www.home-assistant.io/components/zeroconf/
zeroconf:

####################################################
### SERVICES                                    ####
####################################################

# https://www.home-assistant.io/components/camera.synology/
camera:
  - platform: synology
    url: !secret nas_url
    username: !secret nas_username
    password: !secret nas_password
    timeout: 15

# Philips Hue
# https://www.home-assistant.io/components/hue/
hue:
  bridges:
    - host: 192.168.0.16
      allow_unreachable: true
      allow_hue_groups: false

# IFTTT
# https://www.home-assistant.io/components/ifttt/
ifttt:
  key: !secret ifttt_secret

# Media Players
media_player:
  - platform: webostv
    host: 192.168.0.9
    mac: 14:C9:13:7C:BB:FE
    name: 'Living Room TV'

# Nest Learning Thermosat
# https://home-assistant.io/components/nest/
nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

# Twilio notifications
# https://www.home-assistant.io/components/twilio/
twilio:
  account_sid: !secret twilio_sid
  auth_token: !secret twilio_token

# WirelessTag
# https://www.home-assistant.io/components/wirelesstag/
wirelesstag:
  username: !secret wirelesstag_username
  password: !secret wirelesstag_password

# Dark Sky
# https://www.home-assistant.io/components/weather.darksky/
weather:
  - platform: darksky
    api_key: !secret darksky_api_key

# Z-Wave
# https://www.home-assistant.io/components/zwave/
zwave:
  usb_path: /dev/ttyACM0
  network_key: !secret zwave_network_key

####################################################
### INCLUDES                                    ####
####################################################

# Automation #
automation: !include_dir_merge_list automation/

# Groups #
group: !include groups.yaml

# Plants #
plant: !include plants.yaml

# Scripts #
script: !include scripts.yaml

# Sensors #
sensor: !include sensors.yaml

# Shell Commands #
shell_command: !include shell_commands.yaml

# Switches #
switch: !include switches.yaml

# Weblinks #
weblink: !include weblinks.yaml

# Zones #
zone: !include zones.yaml

####################################################
#                                                  #
#            END OF CONFIGURATION FILE             #
#                                                  #
####################################################
