##########################################################
### Home Assistant Configuration                      ####
##########################################################

homeassistant:
  # Name of the location where Home Assistant is running
  name: 'Otteropolis'

  # Location required to calculate the time the sun rises and sets
  latitude: !secret ha_latitude
  longitude: !secret ha_longitude

  # Impacts weather/sunrise data (altitude above sea level)
  elevation: !secret ha_elevation

  # 'metric' for Metric, 'imperial' for Imperial
  unit_system: imperial

  # Pick yours from here:
  # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret ha_time_zone

  # Customizations
  customize: !include_dir_merge_named customize/

  # Packages
  packages: !include_dir_named packages/

####################################################
### GENERAL                                     ####
####################################################

# Cloud
# https://www.home-assistant.io/components/cloud/
cloud:
  alexa:
    filter:
      exclude_domains:
        - group
        - automation
        - alert
      exclude_entities:
        - light.hgrp0000000254
        - switch.raspberry_pi
        - switch.pc
        - switch.imac

# Enables configuration UI
# https://home-assistant.io/components/config/
config:

# Allows you to issue voice commands from the frontend
# https://www.home-assistant.io/components/conversation/
conversation:

# https://www.home-assistant.io/components/device_tracker
device_tracker:
  - platform: netgear
    host: 192.168.0.1
    username: !secret netgear_username
    password: !secret netgear_password
    interval_seconds: 60
    consider_home: 180
    new_device_defaults:
      track_new_devices: False
      hide_if_away: False

# Discover some devices automatically
# https://www.home-assistant.io/components/discovery/
discovery:

# Enables the frontend
# https://www.home-assistant.io/components/frontend/
frontend:
  javascript_version: latest

# Enables support for tracking state changes over time.
# https://home-assistant.io/components/history/
history:

# iOS
# https://www.home-assistant.io/components/ios/
ios:

# View all events in a logbook
# https://www.home-assistant.io/components/logbook/
logbook:

# Enables a map showing the location of tracked devices
# https://www.home-assistant.io/components/map/
map:

# Notifications
# https://www.home-assistant.io/components/notify.twilio_sms/
notify:
  - name: sms
    platform: twilio_sms
    from_number: !secret twilio_number

# Text to speech
tts:
  - platform: google

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  include_used_components: true

# Zeroconf/Avahi/Bonjour
# https://www.home-assistant.io/components/zeroconf/
zeroconf:

####################################################
### SERVICES                                    ####
####################################################

# https://www.home-assistant.io/components/camera.synology/
camera:
  - platform: synology
    url: !secret nas_url
    username: !secret nas_username
    password: !secret nas_password
    timeout: 15

# Philips Hue
# https://www.home-assistant.io/components/hue/
hue:
  bridges:
    - host: 192.168.0.16
      allow_unreachable: true
      allow_hue_groups: false

# IFTTT
# https://www.home-assistant.io/components/ifttt/
ifttt:
  key: !secret ifttt_secret

# Media Players
media_player:
  - platform: webostv
    host: 192.168.0.9
    mac: 14:C9:13:7C:BB:FE
    name: 'Living Room TV'

# Twilio notifications
# https://www.home-assistant.io/components/twilio/
twilio:
  account_sid: !secret twilio_sid
  auth_token: !secret twilio_token

# Z-Wave
# https://www.home-assistant.io/components/zwave/
zwave:
  usb_path: /dev/ttyACM0
  network_key: !secret zwave_network_key

####################################################
### INCLUDES                                    ####
####################################################

# Groups #
group: !include groups.yaml

# Scripts #
script: !include scripts.yaml

# Sensors #
sensor: !include sensors.yaml

# Shell Commands #
shell_command: !include shell_commands.yaml

# Switches #
switch: !include switches.yaml

# Weblinks #
weblink: !include weblinks.yaml

####################################################
#                                                  #
#            END OF CONFIGURATION FILE             #
#                                                  #
####################################################
