### sensors.yaml

##################################
#### TIME/DATE                ####
##################################

- platform: time_date
  display_options:
      - 'time'
      - 'date'

##################################
#### Speed Test               ####
##################################

- platform: speedtest
  minute: 30
  hour:
    - 0
    - 6
    - 12
    - 18
  monitored_conditions:
    - ping
    - download
    - upload

##################################
#### Nest                     ####
##################################

- platform: nest
  monitored_conditions:
    - 'temperature'
    - 'target'
    - 'humidity'
    - 'operation_mode'
    - 'co_status'
    - 'smoke_status'

##################################
#### Weather                  ####
##################################

- platform: darksky
  api_key: !secret darksky_api_key
  monitored_conditions:
    - summary
    - daily_summary
    - temperature
    - apparent_temperature
    - humidity
    - pressure
    - precip_type
    - precip_intensity
    - precip_probability
    - visibility
    - cloud_cover
    - wind_speed
  units: us

##################################
#### System                   ####
##################################

- platform: cpuspeed
  name: CPU

- platform: systemmonitor
  resources:
    - type: memory_free
    - type: memory_use_percent
    - type: processor_use
    - type: since_last_boot
