### sensors.yaml

##################################
#### TIME/DATE                ####
##################################

- platform: time_date
  display_options:
      - 'time'
      - 'date'

##################################
#### Speed Test               ####
##################################

- platform: speedtest
  minute: 30
  hour:
    - 0
    - 6
    - 12
    - 18
  monitored_conditions:
    - ping
    - download
    - upload

##################################
#### Nest                     ####
##################################

- platform: nest
  monitored_conditions:
    - 'temperature'
    - 'target'
    - 'humidity'
    - 'mode'
    - 'co_status'
    - 'smoke_status'

##################################
#### Weather                  ####
##################################

- platform: forecast
  api_key: !secret forecast_api_key
  monitored_conditions:
    - summary
    - daily_summary
    - temperature
    - apparent_temperature
    - humidity
    - pressure
    - precip_type
    - precip_intensity
    - precip_probability
    - visibility
    - cloud_cover
    - wind_speed
  units: us
