### ui-lovelace.yaml
# https://www.home-assistant.io/lovelace

####################################################
#                                                  #
#                 Lovelace UI                      #
#                                                  #
####################################################

title: Otteropolis

# Exclude entities from "Unused entities" view
excluded_entities:
  - weblink.router

views:
    # Specify a tab icon if you want the view tab to be an icon.
  - icon: mdi:home-assistant
    # Title of the view. Will be used as the tooltip for tab icon
    title: Home
    # Optional unique id for direct access /lovelace/${id}
    id: home
    # Optional background (overwrites the global background).
    background: radial-gradient(crimson, skyblue)
    # Each view can have a different theme applied. Theme should be defined in the frontend.
    theme: dark-mode
    # The cards to show on this view.
    cards:
        # The filter card will filter entities for their state
      - type: vertical-stack
        cards:
          - type: entity-filter
            entities:
              - entity: device_tracker.michaels_iphone
                name: Michael
              - entity: device_tracker.julias_iphone
                name: Julia
            state_filter:
              - 'home'
            card:
              type: glance
              title: People that are home
          - type: entities
            show_header_toggle: false
            entities:
              - group.house_mode

        # The picture entity card will represent an entity with a picture
      - type: picture-entity
        image: https://www.home-assistant.io/images/default-social.png
        entity: light.julias_closet

      - type: weather-forecast
        entity: weather.dark_sky

      - type: picture-glance
        title: Dining Room
        entities:
          - light.dining_room_spot
        camera_image: camera.dining_room

      - type: vertical-stack
        cards:
          - type: plant-status
            entity: plant.diamond_crown

          - type: plant-status
            entity: plant.laundry_room

    # Specify a tab icon if you want the view tab to be an icon.
  - icon: mdi:lightbulb-outline
    # Title of the view. Will be used as the tooltip for tab icon
    title: Devices
    # Optional unique id for direct access /lovelace/${id}
    id: devices
    # Optional background (overwrites the global background).
    background: radial-gradient(crimson, skyblue)
    # Each view can have a different theme applied. Theme should be defined in the frontend.
    theme: dark-mode
    # The cards to show on this view.
    cards:
        # Entities card will take a list of entities and show their state.
      - type: entities
        # Title of the entities card
        title: Lights
        # The entities here will be shown in the same order as specified.
        # Each entry is an entity ID or a map with extra options.
        entities:
          - light.dresser_lamp
          - light.nightstand_lamp
          - light.michaels_closet
          - light.julias_closet
          - light.table_light
          - switch.aeotec_zw096_smart_switch_6_switch
          - light.aeotec_zw099_smart_dimmer_6_level_2
          - light.dining_room_spot
          - light.guest_room_storage
          - light.linear_lb60z1_dimmable_led_light_bulb_level
          - light.linear_lb60z1_dimmable_led_light_bulb_level_2

      - type: picture-glance
        title: Living room
        entities:
          - climate.living_room
          - light.table_light
          - switch.aeotec_zw096_smart_switch_6_switch
          - light.aeotec_zw099_smart_dimmer_6_level_2
        image: /local/living_room.jpg

        # The markdown card will render markdown text.
      - type: markdown
        title: Lovelace
        content: >
          Welcome to your **Lovelace UI**.

        # Entities card will take a list of entities and show their state.
      - type: entities
        # Title of the entities card
        title: Automations
        # The entities here will be shown in the same order as specified.
        # Each entry is an entity ID or a map with extra options.
        entities:
          - automation.master_bedroom_motion
          - automation.living_room_motion
          - automation.michael_closet_lighting
          - automation.julia_closet_lighting
          - automation.guest_closet_lighting
          - automation.guest_storage_lighting

      - type: entities
        title: Column 3
        show_header_toggle: false
        entities:
          - script.manual_config_backup
          - script.reload_config
          - script.update_hass
          - script.restart_hass

####################################################
#                                                  #
#            END OF CONFIGURATION FILE             #
#                                                  #
####################################################
