### ui-lovelace.yaml
# https://www.home-assistant.io/lovelace

####################################################
#                                                  #
#                 Lovelace UI                      #
#                                                  #
####################################################

title: Otteropolis

# Exclude entities from "Unused entities" view
excluded_entities:
  - weblink.router_admin
  - weblink.swtich_admin
  - weblink.wifi_admin

resources:
  - url: /local/alarm_control_panel-card.js?v=1
    type: js
  - url: /local/thermostat-card.js?v=1
    type: module

views:
  - icon: mdi:home-assistant
    title: Home
    id: home
    background: radial-gradient(crimson, skyblue)
    theme: dark-mode
    cards:
      - type: vertical-stack
        cards:
          - type: entity-filter
            entities:
              - entity: input_select.michaels_status
              - entity: input_select.julias_status
            state_filter:
              - 'Home'
              - 'Arriving'
              - 'Departing'
            card:
              type: glance
              title: People that are home
          - type: custom:alarm_control_panel-card
            entity: alarm_control_panel.alarm_system
            title: Alarm System
            states:
              - arm_away
              - arm_night
          - type: entities
            show_header_toggle: false
            entities:
              - sensor.house_mode
              - input_boolean.night_mode
              - input_boolean.guest_mode
              - sensor.household

      - type: weather-forecast
        entity: weather.dark_sky

      - type: entities
        title: Favorites
        entities:
          - light.dresser_lamp
          - light.nightstand_lamp
          - type: divider
          - light.table_light
          - light.living_room_bookshelf_lamp
          - light.living_room_floor_lamp
          - type: divider
          - light.dining_room_spot

      - type: custom:thermostat-card
        title: Nest
        entity: climate.living_room
        chevron_size: 50
        step: 1

  - icon: mdi:lightbulb-outline
    title: Devices
    id: devices
    background: radial-gradient(crimson, skyblue)
    theme: dark-mode
    cards:
      - type: entities
        title: Lights
        entities:
          - light.dresser_lamp
          - light.nightstand_lamp
          - light.michaels_closet
          - light.julias_closet
          - type: divider
          - light.table_light
          - light.living_room_bookshelf_lamp
          - light.living_room_floor_lamp
          - type: divider
          - light.dining_room_spot
          - type: divider
          - light.guest_bedroom_storage
          - light.guest_bedroom_closet
          - type: divider
          - light.garage_storage
          - type: divider
          - light.dungeon

  - icon: mdi:floor-plan
    title: Rooms
    id: rooms
    background: radial-gradient(blueviolet, skyblue)
    theme: dark-mode
    cards:
      - type: picture-glance
        title: Living room
        entities:
          - climate.living_room
          - light.table_light
          - switch.living_room_bookshelf_lamp
          - light.living_room_floor_lamp
        image: /local/living_room.jpg?v=1

      - type: picture-glance
        title: Master Bedroom
        entities:
          - light.dresser_lamp
          - light.nightstand_lamp
        image: /local/master_bedroom.jpg?v=1

      - type: picture-glance
        title: Guest Bedroom
        entities:
          - light.guest_bedroom_storage
          - light.guest_bedroom_closet
        image: /local/guest_bedroom.jpg?v=1

      - type: picture-glance
        title: Dining Room
        entities:
          - light.dining_room_spot
        camera_image: camera.dining_room

  - icon: mdi:camcorder
    title: Cameras
    id: cameras
    background: radial-gradient(blueviolet, skyblue)
    theme: dark-mode
    cards:
      - type: picture-entity
        title: Dining Room
        entity: camera.dining_room

  - icon: mdi:access-point
    title: Sensors
    id: sensors
    background: radial-gradient(blueviolet, skyblue)
    theme: dark-mode
    cards:
      - type: entities
        title: Temperature Sensors
        entities:
          - sensor.laundry_room_flood_sensor_temperature
          - sensor.living_room_motion_sensor_temperature
          - sensor.living_room_thermostat_temperature
          - sensor.master_bedroom_motion_sensor_temperature
          - sensor.wirelesstag_laundry_room_temperature
          - sensor.wirelesstag_diamond_crown_humidor_temperature

      - type: entities
        title: Motion Sensors
        entities:
          - binary_sensor.master_bedroom_motion_sensor
          - binary_sensor.living_room_motion_sensor

      - type: entities
        title: Door Sensors
        entities:
          - binary_sensor.entrance_front_door_contact
          - binary_sensor.guest_bedroom_closet_door_contact
          - binary_sensor.guest_bedroom_storage_door_contact
          - binary_sensor.julias_closet_door_contact
          - binary_sensor.michaels_closet_door_contact

      - type: entities
        title: Batteries
        entities:
          - sensor.wirelesstag_laundry_room_battery
          - sensor.wirelesstag_diamond_crown_humidor_battery
          - sensor.guest_bedroom_closet_door_contact_battery
          - sensor.guest_bedroom_storage_door_contact_battery
          - sensor.guest_bedroom_smoke_and_carbon_monoxide_detector_battery
          - sensor.julias_closet_door_contact_battery
          - sensor.julias_iphone_battery_level
          - sensor.laundry_room_flood_sensor_battery
          - sensor.laundry_room_smoke_and_carbon_monoxide_detector_battery
          - sensor.living_room_motion_sensor_battery
          - sensor.living_room_nest_protect_battery_health
          - sensor.master_bedroom_smoke_and_carbon_monoxide_detector_battery
          - sensor.michaels_closet_door_contact_battery
          - sensor.michaels_iphone_battery_level

      - type: history-graph
        title: 'Presence History'
        entities:
          - sensor.household
          - input_select.julias_status
          - input_select.michaels_status
          - sensor.house_mode

      - type: vertical-stack
        cards:
          - type: plant-status
            entity: plant.diamond_crown

          - type: plant-status
            entity: plant.laundry_room

  - icon: mdi:robot
    title: Automations
    id: automations
    background: radial-gradient(orange, skyblue)
    theme: dark-mode
    cards:
      - type: entities
        title: Lighting Automations
        entities:
          - automation.master_bedroom_motion
          - automation.living_room_motion
          - automation.michaels_closet_lighting
          - automation.julias_closet_lighting
          - automation.guest_bedroom_closet_lighting
          - automation.guest_bedroom_storage_lighting
      - type: entities
        title: Presence Automations
        entities:
          - automation.auto_away
          - automation.auto_home

####################################################
#                                                  #
#            END OF CONFIGURATION FILE             #
#                                                  #
####################################################
