### ui-lovelace.yaml
# https://www.home-assistant.io/lovelace

####################################################
#                                                  #
#                 Lovelace UI                      #
#                                                  #
####################################################

title: Otteropolis

# Exclude entities from "Unused entities" view
excluded_entities:

resources:
  - url: https://fonts.googleapis.com/css?family=Open+Sans&display=swap
    type: css
  - url: /local/js/alarm_control_panel-card.js?v=5
    type: js
  - url: /community_plugin/bignumber-card/bignumber-card.js
    type: module
  - url: /community_plugin/banner-card/banner-card.js
    type: module
  - url: /community_plugin/button-card/button-card.js
    type: module
  - url: /community_plugin/decluttering-card/decluttering-card.js
    type: module
  - url: /community_plugin/lovelace-card-mod/card-mod.js
    type: module
  - url: /community_plugin/lovelace-markdown-mod/markdown-mod.js
    type: module
  - url: /community_plugin/mini-graph-card/mini-graph-card.js
    type: module
  - url: /community_plugin/mini-media-player/mini-media-player.js
    type: module
  - url: /community_plugin/monster-card/monster-card.js
    type: module
  - url: /community_plugin/roku-card/roku-card.js
    type: module
  - url: /community_plugin/vertical-stack-in-card/vertical-stack-in-card.js
    type: js
  - url: /community_plugin/weather-card/weather-card.js
    type: module

decluttering_templates:
  camera_button:
    card:
      type: custom:button-card
      entity: '[[entity]]'
      icon: '[[icon]]'
      show_state: false
      show_icon: true
      show_name: false
      tap_action:
        action: toggle
      style: |
        ha-card {
          # font-family: 'Open Sans', sans-serif;
          padding-top: 10px !important;
          background-color: rgba(0, 0, 0, 0);
          -webkit-box-shadow: none;
          -moz-box-shadow: none;
          box-shadow: none;
        }    
  nest_button:
    default:
      - show_state: true
      - show_name: false
    card:
      type: custom:button-card
      entity: '[[entity]]'
      show_last_changed: true
      show_state: '[[show_state]]'
      show_icon: true
      show_name: '[[show_name]]'
      name: '[[name]]'
      state: '[[state]]'
      tap_action:
        action: more-info
      style: |
        ha-card {
          font-family: 'Open Sans', sans-serif;
          padding-top: 15px !important;
          background-color: rgba(0, 0, 0, 0);
          -webkit-box-shadow: none;
          -moz-box-shadow: none;
          box-shadow: none;
        }
        ha-icon {
          width: 60% !important;
        }
        img {
          width: 100%;
        }
        #img-cell {
          background-color: #F5F5F5;
          border-radius: 50px;
          height: 50px !important;
          width: 50px !important;
        }
        #state {
          padding-top: 5px;
        }
        #label {
          font-size: 70%;
        }
  nest_picture_button:
    card:
      type: custom:button-card
      entity: '[[entity]]'
      show_state: true
      show_icon: true
      show_name: false
      show_entity_picture: true
      entity_picture: '[[entity_picture]]'
      tap_action:
        action: more-info
      style: |
        ha-card {
          font-family: 'Open Sans', sans-serif;
          padding-top: 15px !important;
          background-color: rgba(0, 0, 0, 0);
          -webkit-box-shadow: none;
          -moz-box-shadow: none;
          box-shadow: none;
        }
        img {
          width: 100% !important;
        }
        #img-cell {
          background-color: #F5F5F5;
          border-radius: 50px;
          height: 50px !important;
          width: 50px !important;
        }
        #state {
          padding-top: 5px;
        }

views:
  - !include lovelace/home_view.yaml
  - !include lovelace/lights_view.yaml

  - icon: mdi:floor-plan
    title: Rooms
    path: rooms
#    background: radial-gradient(blueviolet, skyblue)
    background: var(--background-image)
#    theme: clear-dark
    cards:
      - type: custom:banner-card
        background: "#EDE7B0"
        heading: "\U0001F6CB Living room"
        link: /lovelace/living_room
        entities:
          - light.table_light
          - light.living_room_bookshelf_lamp
          - light.living_room_floor_lamp
          - entity: sensor.living_room_motion_sensor_luminance
            name: Lux
          - entity: climate.living_room
            name: Thermostat

      - type: custom:banner-card
        background: "#B0C2ED"
        heading: "\U0001F6CC Bedroom"
        link: /lovelace/master_bedroom
        entities:
          - light.dresser_lamp
          - light.nightstand_lamp
          - entity: sensor.master_bedroom_motion_sensor_relative_humidity
            name: Humidity
          - entity: sensor.master_bedroom_motion_sensor_temperature
            name: Temperature
          - entity: sensor.master_bedroom_motion_sensor_luminance
            name: Lux
          - entity: binary_sensor.master_bedroom_motion_sensor
            name: Motion
            map_state:
              on: mdi:walk
              off: mdi:run

      - type: custom:banner-card
        background: "#B0C2ED"
        heading: "\U0001F374 Dining Room"
        link: /lovelace/dining_room
        entities:
          - light.dining_room_spot
          - camera.dining_room
          - entity: media_player.dining_room
            when: playing

      - type: picture-glance
        title: Living room
        entities:
          - climate.living_room
          - light.table_light
          - light.living_room_bookshelf_lamp
          - light.living_room_floor_lamp
        image: /local/img/living_room.jpg?v=1

      - type: picture-glance
        title: Master Bedroom
        entities:
          - light.dresser_lamp
          - light.nightstand_lamp
        image: /local/img/master_bedroom.jpg?v=1

      - type: picture-glance
        title: Guest Bedroom
        entities:
          - light.guest_bedroom_storage
          - light.guest_bedroom_closet
        image: /local/img/guest_bedroom.jpg?v=1

      - type: picture-glance
        title: Dining Room
        entities:
          - light.dining_room_spot
        camera_image: camera.dining_room

  - icon: mdi:camcorder
    title: Cameras
    path: cameras
#    background: radial-gradient(blueviolet, skyblue)
    background: var(--background-image)
    theme: clear-dark
    cards:
      - type: picture-entity
        title: Dining Room
        entity: camera.dining_room

  - icon: mdi:television-classic
    title: Media
    path: media
#    background: radial-gradient(blueviolet, skyblue)
    background: var(--background-image)
    theme: clear-dark
    cards:
      - type: custom:roku-card
        entity: media_player.garage
        name: Garage TV
        theme: darkpurple
        tv: true

      - type: glance
        title: Living Room Activities
        entities:
          - entity: switch.apple_tv
            tap_action: toggle
          - entity: switch.lg_tv
            tap_action: toggle
          - entity: switch.xbox_one
            tap_action: toggle

      - type: conditional
        conditions:
          - entity: media_player.living_room_tv
            state: 'playing'
        card:
          type: media-control
          entity: media_player.living_room_tv

      - type: custom:mini-media-player
        entity: media_player.living_room
        hide:
          power: true
          icon: true
          source: true
        speaker_group:
          platform: sonos
          show_group_count: true
          entities:
            - entity_id: media_player.dining_room
              name: Sonos Dining Room
            - entity_id: media_player.living_room
              name: Sonos Living Room
            - entity_id: media_player.office
              name: Sonos Office

  - icon: mdi:access-point
    title: Sensors
    path: sensors
    background: var(--background-image)
#    background: radial-gradient(blueviolet, skyblue)
#    theme: clear-dark
    cards:
      - type: custom:monster-card
        card:
          type: entities
          title: Temperature Sensors
          show_header_toggle: false
        filter:
          include:
            - domain: sensor
              attributes:
                device_class: temperature

      - type: custom:monster-card
        card:
          type: entities
          title: Motion Sensors
          show_header_toggle: false
        filter:
          include:
            - domain: binary_sensor
              attributes:
                device_class: motion

      - type: custom:monster-card
        card:
          type: entities
          title: Door Sensors
          show_header_toggle: false
        filter:
          include:
            - domain: binary_sensor
              attributes:
                device_class: door
            - domain: binary_sensor
              attributes:
                device_class: garage-door

      - type: custom:monster-card
        card:
          type: entities
          title: Batteries
          show_header_toggle: false
        filter:
          include:
            - domain: sensor
              entity_id: "*battery"

      - type: history-graph
        title: 'Presence History'
        entities:
          - sensor.household
          - input_select.julias_status
          - input_select.michaels_status
          - alarm_control_panel.alarm_system

      - type: custom:vertical-stack-in-card
        cards:
          - type: custom:mini-graph-card
            name: DIAMOND CROWN HUMIDOR
            entities:
              - entity: sensor.wirelesstag_diamond_crown_humidor_humidity
                name: Humidity
                color: blue
            show:
              legend: false
              labels: true
          - type: horizontal-stack
            cards:
              - type: sensor
                name: BATTERY
                entity: sensor.wirelesstag_diamond_crown_humidor_battery
                graph: none
              - type: custom:mini-graph-card
                name: TEMPERATURE
                entities:
                  - entity: sensor.wirelesstag_diamond_crown_humidor_temperature
                show:
                  graph: bar
                  legend: false

      - type: custom:vertical-stack-in-card
        cards:
          - type: custom:mini-graph-card
            name: DESKTOP HUMIDOR
            entities:
              - entity: sensor.wirelesstag_desktop_humidor_humidity
                name: Humidity
                color: blue
            show:
              legend: false
              labels: true
          - type: horizontal-stack
            cards:
              - type: sensor
                name: BATTERY
                entity: sensor.wirelesstag_desktop_humidor_battery
                graph: none
              - type: custom:mini-graph-card
                name: TEMPERATURE
                entities:
                  - entity: sensor.wirelesstag_desktop_humidor_temperature
                    color: red
                show:
                  graph: bar
                  legend: false

      - type: custom:mini-graph-card
        name: Network
        icon: mdi:server
        entities:
          - entity: sensor.speedtest_download
            name: DOWNLOAD
          - entity: sensor.speedtest_upload
            name: UPLOAD
          - entity: sensor.speedtest_ping
            name: PING
            y_axis: secondary

  - !include lovelace/automations_view.yaml
  - !include lovelace/settings_view.yaml

####################################################
#                                                  #
#            END OF CONFIGURATION FILE             #
#                                                  #
####################################################
