### ui-lovelace.yaml
# https://www.home-assistant.io/lovelace

####################################################
#                                                  #
#                 Lovelace UI                      #
#                                                  #
####################################################

title: Otteropolis

# Exclude entities from "Unused entities" view
excluded_entities:

resources:
  - url: /local/js/alarm_control_panel-card.js?v=5
    type: js

views:
  - icon: mdi:home-assistant
    title: Home
    id: home
    background: radial-gradient(crimson, skyblue)
    theme: dark-mode
    cards:
      - type: vertical-stack
        cards:
          - type: entity-filter
            entities:
              - entity: input_select.michaels_status
              - entity: input_select.julias_status
            state_filter:
              - 'Home'
              - 'Arriving'
              - 'Departing'
            card:
              type: glance
              title: People that are home
          - type: alarm-panel
            entity: alarm_control_panel.alarm_system
            title: Alarm System
#            display_letters: true
#            scale: 15px
            states:
              - arm_away
              - arm_home
              - arm_night
              - arm_custom_bypass
#            labels:
#              ui.card.alarm_control_panel.arm_custom_bypass: Arm Custom
#          - type: entities
#            show_header_toggle: false
#            entities:
#              - sensor.house_mode
#              - input_boolean.night_mode
#              - input_boolean.guest_mode
#              - sensor.household

      - type: thermostat
        entity: climate.living_room

      - type: entities
        title: Favorites
        entities:
          - light.dresser_lamp
          - light.nightstand_lamp
          - type: divider
          - light.table_light
          - light.living_room_bookshelf_lamp
          - light.living_room_floor_lamp
          - type: divider
          - light.dining_room_spot
          - type: divider
          - cover.garage_door_opener
          - type: divider
          - switch.basement_task_light

      - type: weather-forecast
        entity: weather.dark_sky

      - type: map
        aspect_ratio: '16:9'
        default_zoom: 16
        entities:
          - device_tracker.julia
          - device_tracker.michael
          - zone.home

  - icon: mdi:lightbulb-outline
    title: Devices
    id: devices
    background: radial-gradient(crimson, skyblue)
    theme: dark-mode
    cards:
      - type: vertical-stack
        cards:
          - type: markdown
            content: >
              ## Living Room
          - type: horizontal-stack
            cards:
              - type: light
                entity: light.table_light
              - type: light
                entity: light.living_room_bookshelf_lamp
          - type: light
            entity: light.living_room_floor_lamp

      - type: vertical-stack
        cards:
          - type: markdown
            content: >
              ## Bedroom
          - type: horizontal-stack
            cards:
              - type: light
                entity: light.dresser_lamp
              - type: light
                entity: light.nightstand_lamp
          - type: horizontal-stack
            cards:
              - type: light
                entity: light.michaels_closet
              - type: light
                entity: light.julias_closet

      - type: vertical-stack
        cards:
          - type: markdown
            content: >
              ## Dining Room
          - type: light
            entity: light.dining_room_spot

      - type: vertical-stack
        cards:
          - type: markdown
            content: >
              ## Garage
          - type: light
            entity: light.garage_storage

      - type: vertical-stack
        cards:
          - type: markdown
            content: >
              ## Guest Bedroom
          - type: horizontal-stack
            cards:
              - type: light
                entity: light.guest_bedroom_storage
                name: Guest Storage
              - type: light
                entity: light.guest_bedroom_closet

      - type: vertical-stack
        cards:
          - type: markdown
            content: >
              ## Basement
          - type: entity-button
            entity: switch.basement_task_light
          - type: light
            entity: light.dungeon

  - icon: mdi:floor-plan
    title: Rooms
    id: rooms
    background: radial-gradient(blueviolet, skyblue)
    theme: dark-mode
    cards:
      - type: picture-glance
        title: Living room
        entities:
          - climate.living_room
          - light.table_light
          - light.living_room_bookshelf_lamp
          - light.living_room_floor_lamp
        image: /local/img/living_room.jpg?v=1

      - type: picture-glance
        title: Master Bedroom
        entities:
          - light.dresser_lamp
          - light.nightstand_lamp
        image: /local/img/master_bedroom.jpg?v=1

      - type: picture-glance
        title: Guest Bedroom
        entities:
          - light.guest_bedroom_storage
          - light.guest_bedroom_closet
        image: /local/img/guest_bedroom.jpg?v=1

      - type: picture-glance
        title: Dining Room
        entities:
          - light.dining_room_spot
        camera_image: camera.dining_room

  - icon: mdi:camcorder
    title: Cameras
    id: cameras
    background: radial-gradient(blueviolet, skyblue)
    theme: dark-mode
    cards:
      - type: picture-entity
        title: Dining Room
        entity: camera.dining_room

  - icon: mdi:television-classic
    title: Media
    id: media
    background: radial-gradient(blueviolet, skyblue)
    theme: dark-mode
    cards:
      - type: glance
        title: Living Room Activities
        entities:
          - entity: switch.apple_tv
            tap_action: toggle
          - entity: switch.lg_tv
            tap_action: toggle
          - entity: switch.xbox_one
            tap_action: toggle

      - type: conditional
        conditions:
          - entity: media_player.living_room_tv
            state: 'playing'
        card:
          type: media-control
          entity: media_player.living_room_tv
  
      - type: media-control
        entity: media_player.living_room

      - type: media-control
        entity: media_player.dining_room

  - icon: mdi:access-point
    title: Sensors
    id: sensors
    background: radial-gradient(blueviolet, skyblue)
    theme: dark-mode
    cards:
      - type: entities
        title: Temperature Sensors
        entities:
          - sensor.laundry_room_flood_sensor_temperature
          - sensor.living_room_motion_sensor_temperature
          - sensor.living_room_thermostat_temperature
          - sensor.master_bedroom_motion_sensor_temperature
          - sensor.wirelesstag_desktop_humidor_temperature
          - sensor.wirelesstag_diamond_crown_humidor_temperature

      - type: entities
        title: Motion Sensors
        entities:
          - binary_sensor.master_bedroom_motion_sensor
          - binary_sensor.living_room_motion_sensor

      - type: entities
        title: Door Sensors
        entities:
          - binary_sensor.entrance_front_door_contact
          - binary_sensor.garage_door_opener
          - binary_sensor.guest_bedroom_closet_door_contact
          - binary_sensor.guest_bedroom_storage_door_contact
          - binary_sensor.julias_closet_door_contact
          - binary_sensor.michaels_closet_door_contact

      - type: entities
        title: Batteries
        entities:
          - sensor.wirelesstag_desktop_humidor_battery
          - sensor.wirelesstag_diamond_crown_humidor_battery
          - sensor.guest_bedroom_closet_door_contact_battery
          - sensor.guest_bedroom_storage_door_contact_battery
          - sensor.guest_bedroom_smoke_and_carbon_monoxide_detector_battery
          - sensor.julias_closet_door_contact_battery
          - sensor.julias_iphone_battery_level
          - sensor.laundry_room_flood_sensor_battery
          - sensor.laundry_room_smoke_and_carbon_monoxide_detector_battery
          - sensor.living_room_motion_sensor_battery
          - sensor.living_room_nest_protect_battery_health
          - sensor.master_bedroom_smoke_and_carbon_monoxide_detector_battery
          - sensor.michaels_closet_door_contact_battery
          - sensor.michaels_iphone_battery_level

      - type: history-graph
        title: 'Presence History'
        entities:
          - sensor.household
          - input_select.julias_status
          - input_select.michaels_status
          - sensor.house_mode

      - type: vertical-stack
        cards:
          - type: plant-status
            entity: plant.diamond_crown_humidor

          - type: plant-status
            entity: plant.desktop_humidor

      - type: entities
        title: System
        entities:
          - sensor.date
          - sensor.time
          - sensor.processor_use
          - sensor.disk_use_percent_home
          - sensor.memory_use_percent
          - sensor.since_last_boot_templated
          - sensor.network_in_eth0
          - sensor.network_out_eth0
          - sensor.load_1m
          - sensor.load_5m
          - sensor.load_15m
          - sensor.current_version

      - type: vertical-stack
        cards:
          - type: gauge
            entity: sensor.speedtest_download
            title: Download Speed
            severity:
              green: 90
              yellow: 45
              red: 0
          - type: gauge
            entity: sensor.speedtest_upload
            title: Upload Speed
            severity:
              green: 90
              yellow: 45
              red: 0
          - type: gauge
            entity: sensor.speedtest_ping
            title: Ping

  - icon: mdi:robot
    title: Automations
    id: automations
    background: radial-gradient(orange, skyblue)
    theme: dark-mode
    cards:
      - type: entities
        title: Lighting Automations
        entities:
          - automation.master_bedroom_motion
          - automation.living_room_motion
          - automation.michaels_closet_lighting
          - automation.julias_closet_lighting
          - automation.guest_bedroom_closet_lighting
          - automation.guest_bedroom_storage_lighting
      - type: entities
        title: Presence Automations
        entities:
          - automation.auto_away
          - automation.auto_home
      - type: entities
        title: Timed Automations
        entities:
          - automation.auto_morning
          - automation.auto_evening
          - automation.auto_night

####################################################
#                                                  #
#            END OF CONFIGURATION FILE             #
#                                                  #
####################################################
