################################################################
## Z-Wave / Device Config
################################################################

################################################
## Door/Window Sensor
################################################

sensor.aeotec_zw120_door_window_sensor_gen5_access_control:
  ignored: true

sensor.aeotec_zw120_door_window_sensor_gen5_alarm_level:
  ignored: true

sensor.aeotec_zw120_door_window_sensor_gen5_alarm_type:
  ignored: true

sensor.aeotec_zw120_door_window_sensor_gen5_sourcenodeid:
  ignored: true

sensor.aeotec_zw120_door_window_sensor_gen5_access_control_2:
  ignored: true

sensor.aeotec_zw120_door_window_sensor_gen5_alarm_level_2:
  ignored: true

sensor.aeotec_zw120_door_window_sensor_gen5_alarm_type_2:
  ignored: true

sensor.aeotec_zw120_door_window_sensor_gen5_sourcenodeid_2:
  ignored: true

sensor.aeotec_zw120_door_window_sensor_gen5_access_control_3:
  ignored: true

sensor.aeotec_zw120_door_window_sensor_gen5_alarm_level_3:
  ignored: true

sensor.aeotec_zw120_door_window_sensor_gen5_alarm_type_3:
  ignored: true

sensor.aeotec_zw120_door_window_sensor_gen5_sourcenodeid_3:
  ignored: true

sensor.fibaro_system_fgk10x_door_opening_sensor_access_control:
  ignored: true

sensor.fibaro_system_fgk10x_door_opening_sensor_alarm_level:
  ignored: true

sensor.fibaro_system_fgk10x_door_opening_sensor_alarm_type:
  ignored: true

sensor.fibaro_system_fgk10x_door_opening_sensor_burglar:
  ignored: true

sensor.fibaro_system_fgk10x_door_opening_sensor_general:
  ignored: true

sensor.fibaro_system_fgk10x_door_opening_sensor_sourcenodeid:
  ignored: true

################################################
## Flood Sensor
################################################

sensor.fibaro_system_fgfs101_zwave_flood_sensor_sourcenodeid:
  ignored: true

################################################
## Garage Door
################################################

sensor.linear_gd00z4_garage_door_opener_remote_controller_sourcenodeid:
  ignored: true

sensor.linear_gd00z4_garage_door_opener_remote_controller_burglar:
  ignored: false

sensor.linear_gd00z4_garage_door_opener_remote_controller_alarm_level:
  ignored: false

sensor.linear_gd00z4_garage_door_opener_remote_controller_alarm_type:
  ignored: false

################################################
## Lights
################################################

light.guest_bedroom_closet:
  refresh_value: true
  delay: 3

light.garage_storage:
  refresh_value: true
  delay: 3

light.dungeon:
  refresh_value: true
  delay: 3

################################################
## Multisensor
################################################

sensor.aeotec_zw100_multisensor_6_alarm_level:
  ignored: true

sensor.aeotec_zw100_multisensor_6_alarm_type:
  ignored: true

sensor.aeotec_zw100_multisensor_6_sourcenodeid:
  ignored: true

sensor.aeotec_zw100_multisensor_6_ultraviolet:
  ignored: true

sensor.fibaro_system_fgms001zw5_motion_sensor_alarm_level:
  ignored: true

sensor.fibaro_system_fgms001zw5_motion_sensor_alarm_type:
  ignored: true

sensor.fibaro_system_fgms001zw5_motion_sensor_general:
  ignored: true

sensor.fibaro_system_fgms001zw5_motion_sensor_sourcenodeid:
  ignored: true

################################################
## Smoke Detectors
################################################

sensor.first_alert_zcombo_smoke_and_carbon_monoxide_detector_alarm_type:
  ignored: true

sensor.first_alert_zcombo_smoke_and_carbon_monoxide_detector_alarm_type_2:
  ignored: true

sensor.first_alert_zcombo_smoke_and_carbon_monoxide_detector_alarm_type_3:
  ignored: true

################################################
## Switch
################################################

sensor.aeotec_zw096_smart_switch_6_current:
  ignored: true

sensor.aeotec_zw096_smart_switch_6_energy:
  ignored: true

sensor.aeotec_zw096_smart_switch_6_power:
  ignored: true

sensor.aeotec_zw096_smart_switch_6_previous_reading:
  ignored: true

sensor.aeotec_zw096_smart_switch_6_voltage:
  ignored: true
