################################################################
## Z-Wave / Device Config
################################################################

################################################
## Garage Door
################################################

sensor.linear_gd00z4_garage_door_opener_remote_controller_sourcenodeid:
  ignored: true

sensor.linear_gd00z4_garage_door_opener_remote_controller_burglar:
  ignored: true

sensor.linear_gd00z4_garage_door_opener_remote_controller_alarm_level:
  ignored: true

sensor.linear_gd00z4_garage_door_opener_remote_controller_alarm_type:
  ignored: true

################################################
## Lights
################################################

light.linear_lb60z1_dimmable_led_light_bulb_level:
  refresh_value: true
  delay: 5

light.linear_lb60z1_dimmable_led_light_bulb_level_2:
  refresh_value: true
  delay: 5

light.linear_lb60z1_dimmable_led_light_bulb_level_3:
  refresh_value: true
  delay: 5
