################################################################
## Packages / Groups / Batteries
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'groups/batteries'

      expose: &expose
        <<: *customize
        homebridge_hidden: false

    ################################################
    ## Group
    ################################################

    group.batteries:
      <<: *customize
      friendly_name: "Batteries"
      icon: mdi:battery

################################################
## Group
################################################

group:
  batteries:
    control: hidden
    entities:
      - sensor.wirelesstag_desktop_humidor_battery
      - sensor.wirelesstag_diamond_crown_humidor_battery
      - sensor.guest_bedroom_closet_door_contact_battery
      - sensor.guest_bedroom_storage_door_contact_battery
      - sensor.guest_bedroom_smoke_and_carbon_monoxide_detector_battery
      - sensor.julias_closet_door_contact_battery
      - sensor.julias_iphone_battery_level
      - sensor.laundry_room_flood_sensor_battery
      - sensor.laundry_room_smoke_and_carbon_monoxide_detector_battery
      - sensor.living_room_motion_sensor_battery
      - sensor.living_room_nest_protect_battery_health
      - sensor.master_bedroom_smoke_and_carbon_monoxide_detector_battery
      - sensor.michaels_closet_door_contact_battery
      - sensor.michaels_iphone_battery_level
