################################################################
## Packages / Groups / Media Components
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'groups/media_components'

      expose: &expose
        <<: *customize
        homebridge_hidden: false

    ################################################
    ## Group
    ################################################

    group.media_components:
      <<: *customize
      friendly_name: "Media Components"
      icon: mdi:audio-video

    group.media_players:
      <<: *customize
      friendly_name: "Media Players"
      icon: mdi:television

################################################
## Group
################################################

group:
  media_components:
    control: hidden
    entities:
      - switch.apple_tv
      - switch.xbox

  media_players:
    control: hidden
    entities:
      - media_player.dining_room
      - media_player.living_room
      - media_player.living_room_tv
