################################################################
## Packages / Groups / Motion
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'groups/motion'

      expose: &expose
        <<: *customize
        homebridge_hidden: false

    ################################################
    ## Group
    ################################################

    group.motion:
      <<: *customize
      friendly_name: "Motion"
      icon: mdi:run

################################################
## Group
################################################

group:
  motion:
    control: hidden
    entities:
      - binary_sensor.master_bedroom_motion_sensor
      - binary_sensor.living_room_motion_sensor
