################################################################
## Packages / Groups / Rooms
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'groups/rooms'

      expose: &expose
        <<: *customize
        homebridge_hidden: false

    ################################################
    ## Group
    ################################################

    group.basement:
      <<: *customize
      friendly_name: "Basement"

    group.dining_room:
      <<: *customize
      friendly_name: "Dining Room"

    group.entry:
      <<: *customize
      friendly_name: "Entry"

    group.garage:
      <<: *customize
      friendly_name: "Garage"

    group.guest_bedroom:
      <<: *customize
      friendly_name: "Guest Bedroom"

    group.kitchen:
      <<: *customize
      friendly_name: "Kitchen"

    group.laundry_room:
      <<: *customize
      friendly_name: "Laundry Room"

    group.living_room:
      <<: *customize
      friendly_name: "Living Room"

    group.master_bedroom:
      <<: *customize
      friendly_name: "Master Bedroom"

    group.master_closets:
      <<: *customize
      friendly_name: "Master Closets"

################################################
## Group
################################################

group:
  basement:
    control: hidden
    entities:
      - light.dungeon_light

  dining_room:
    control: hidden
    entities:
      - light.dining_room_spot
      - media_player.dining_room
      - camera.dining_room

  entry:
    control: hidden
    entities:
      - binary_sensor.aeotec_zw112_door_window_sensor_6_sensor

  garage:
    control: hidden
    entities:
      - light.garage_storage
      - binary_sensor.garage_entry_contact

  guest_bedroom:
    control: hidden
    entities:
      - light.guest_closet
      - binary_sensor.fibaro_system_fgk10x_door_opening_sensor_sensor
      - automation.guest_closet_lighting
      - light.guest_room_storage
      - binary_sensor.aeotec_zw120_door_window_sensor_gen5_sensor_3
      - automation.guest_storage_lighting

  kitchen:
    control: hidden
    entities:
      - zwave.aeotec_zw117_range_extender_6

  laundry_room:
    control: hidden
    entities:
      - binary_sensor.fibaro_system_fgfs101_zwave_flood_sensor_sensor
      - sensor.fibaro_system_fgfs101_zwave_flood_sensor_temperature
      - zwave.aeotec_zw117_range_extender_6_2

  living_room:
    control: hidden
    entities:
      - climate.living_room
      - sensor.living_room_thermostat_operation_mode
      - sensor.living_room_thermostat_humidity
      - sensor.living_room_nest_protect_co_status
      - sensor.living_room_nest_protect_smoke_status
      - light.table_light
      - switch.aeotec_zw096_smart_switch_6_switch
      - light.aeotec_zw099_smart_dimmer_6_level_2
      - binary_sensor.living_room_motion_sensor
      - sensor.living_room_motion_sensor_temperature
      - sensor.living_room_motion_sensor_luminance
      - sensor.living_room_motion_sensor_seismic_intensity
      - sensor.living_room_motion_sensor_burglar
      - sensor.living_room_motion_sensor_battery
      - automation.living_room_motion

  master_bedroom:
    control: hidden
    entities:
      - light.dresser_lamp
      - light.nightstand_lamp
      - sensor.master_bedroom_smoke_and_carbon_monoxide_detector_alarm_level
      - binary_sensor.master_bedroom_motion_sensor
      - sensor.master_bedroom_motion_sensor_burglar
      - sensor.master_bedroom_motion_sensor_temperature
      - sensor.master_bedroom_motion_sensor_relative_humidity
      - sensor.master_bedroom_motion_sensor_luminance
      - automation.master_bedroom_motion

  master_closets:
    control: hidden
    entities:
      - light.michaels_closet
      - binary_sensor.michaels_closet_door_contact
      - sensor.michaels_closet_door_contact_burglar
      - sensor.michaels_closet_door_contact_battery
      - automation.michaels_closet_lighting
      - light.julias_closet
      - binary_sensor.julias_closet_door_contact
      - sensor.julias_closet_door_contact_burglar
      - sensor.julias_closet_door_contact_battery
      - automation.julias_closet_lighting
