################################################################
## Packages / Groups / Temperature
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'groups/temperature'

      expose: &expose
        <<: *customize
        homebridge_hidden: false

    ################################################
    ## Group
    ################################################

    group.temperature:
      <<: *customize
      friendly_name: "Temperature"
      icon: mdi:thermometer

################################################
## Group
################################################

group:
  temperature:
    control: hidden
    entities:
      - sensor.laundry_room_flood_sensor_temperature
      - sensor.living_room_motion_sensor_temperature
      - sensor.living_room_thermostat_temperature
      - sensor.master_bedroom_motion_sensor_temperature
      - sensor.wirelesstag_desktop_humidor_temperature
      - sensor.wirelesstag_diamond_crown_humidor_temperature
