set_home_mode:
  description: 'New home mode for surveilance station. Valid modes are "away" or "home".'
  fields:
    home_mode:
      description: True to turn on home mode, false to turn it off.
      example: 'away'
