# Follow master bedroom lamps when guest automation active
- alias: "Turn On Living Room Lights Lamp When Motion"
  trigger:
    platform: state
    entity_id: sensor.aeotec_zw100_multisensor_6_burglar
    from: '0'
    to: '8'
  action:
    - service: light.turn_on
      entity_id: light.aeotec_zw099_smart_dimmer_6_level_2
      data:
        brightness: 70
    - service: light.turn_on
      entity_id: light.table_light
    - service: switch.turn_on
      entity_id: switch.aeotec_zw096_smart_switch_6_switch
