### automation/upgrade.yaml

# Send a notification when and update is available
alias: 'Auto Update'
trigger:
  platform: state
  entity_id: updater.updater
action:
  - service: notify.twilio
    data:
      message: 'Installing update for Home Assistant.'
      target:
        - !secret mobile_michael
  - service: shell_command.upgrade
