################################################################
## Packages / Alarm
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'alarm'

      expose: &expose
        <<: *customize
        homebridge_hidden: false

    ################################################
    ## Alarm Control Panel
    ################################################

    alarm_control_panel.alarm_system:
      <<: *customize
      friendly_name: "Alarm System"

    ################################################
    ## Automation
    ################################################

    automation.trigger_alarm_on_motion:
      <<: *customize
      friendly_name: "Trigger Alarm on Motion"

################################################
## Alarm Control Panel
################################################

alarm_control_panel:
  - platform: manual
    name: alarm_system
    code: !secret alarm_code
    pending_time: 45
    delay_time: 45
    trigger_time: 120
    disarmed:
      trigger_time: 0
    armed_home:
      pending_time: 0
      delay_time: 0
    armed_night:
      pending_time: 0
      delay_time: 0

################################################
## Automation
################################################

automation:
  - alias: trigger_alarm_on_motion
    trigger:
      - platform: state
        entity_id: binary_sensor.master_bedroom_motion_sensor
        from: 'off'
        to: 'on'
      - platform: state
        entity_id: binary_sensor.living_room_motion_sensor
        from: 'off'
        to: 'on'
    condition:
      - condition: state
        entity_id: alarm_control_panel.alarm_system
        state: 'armed_away'
    action:
      service: alarm_control_panel.alarm_trigger
      entity_id: alarm_control_panel.alarm_system
