################################################################
## Packages / Alarm
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'alarm'

      expose: &expose
        <<: *customize
        homebridge_hidden: false

    ################################################
    ## Alarm Control Panel
    ################################################

    alarm_control_panel.alarm_system:
      <<: *customize
      friendly_name: "Alarm System"

    ################################################
    ## Automation
    ################################################

    automation.alarm_startup_state:
      <<: *customize
      friendly_name: "Arm Alarm on System Startup"
      icon: mdi:alarm

    automation.trigger_alarm_on_motion:
      <<: *customize
      friendly_name: "Trigger Alarm on Motion"

    automation.alarm_triggered_notification:
      <<: *customize
      friendly_name: "Send Notification on Alarm Trigger"
      icon: mdi:message-text

################################################
## Alarm Control Panel
################################################

alarm_control_panel:
  - platform: manual
    name: alarm_system
    code: !secret alarm_code
    pending_time: 45
    delay_time: 45
    trigger_time: 120
    disarmed:
      trigger_time: 0
    armed_home:
      pending_time: 0
      delay_time: 0
    armed_night:
      pending_time: 0
      delay_time: 0

################################################
## Automation
################################################

automation:
  - alias: alarm_startup_state
    initial_state: true
    trigger:
      - platform: homeassistant
        event: start
      - platform: time
        seconds: '/5'
    action:
      - service: automation.turn_off
        data:
          entity_id: automation.alarm_startup_state
      - service_template: >-
          {% if is_state('sensor.household', 'Vacation') or is_state('sensor.household', 'Away') %}
            alarm_control_panel.alarm_arm_away
          {% else %}
            alarm_control_panel.alarm_arm_home
          {% endif %}
        entity_id: alarm_control_panel.alarm_system
        data:
          code: !secret alarm_code

  - alias: trigger_alarm_on_motion
    trigger:
      - platform: state
        entity_id: binary_sensor.master_bedroom_motion_sensor
        from: 'off'
        to: 'on'
      - platform: state
        entity_id: binary_sensor.living_room_motion_sensor
        from: 'off'
        to: 'on'
    condition:
      - condition: state
        entity_id: alarm_control_panel.alarm_system
        state: 'armed_away'
    action:
      service: alarm_control_panel.alarm_trigger
      entity_id: alarm_control_panel.alarm_system

  - alias: alarm_triggered_notification
    trigger:
      - platform: state
        entity_id: alarm_control_panel.alarm_system
        to: 'triggered'
    action:
      - service: notify.sms
        data:
          message: 'ALARM TRIGGERED!!! {{ states[states.alarm_control_panel.alarm_system.attributes.changed_by.split(".")[0]][ states.alarm_control_panel.alarm_system.attributes.changed_by.split(".")[1]].name }}'
          target:
            - !secret mobile_michael
