################################################################
## Packages / Alarm
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'alarm'

      expose: &expose
        <<: *customize
        homebridge_hidden: false

    ################################################
    ## Alarm Control Panel
    ################################################

    alarm_control_panel.alarm_system:
      <<: *customize
      friendly_name: "Alarm System"

    ################################################
    ## Automation
    ################################################

    automation.persistence_subscribe_alarm_control_panel:
      <<: *customize
      friendly_name: "Persistence Subscribe (Alarm Control Panel)"
      icon: mdi:alarm

    automation.alarm_startup_state:
      <<: *customize
      friendly_name: "Arm Alarm on System Startup"
      icon: mdi:alarm

    automation.trigger_alarm_on_motion:
      <<: *customize
      friendly_name: "Trigger Alarm on Motion"

    automation.alarm_triggered_notification:
      <<: *customize
      friendly_name: "Send Notification on Alarm Trigger"
      icon: mdi:message-text

################################################
## Alarm Control Panel
################################################

alarm_control_panel:
  - platform: manual_mqtt
    name: alarm_system
    state_topic: home-assistant/alarm
    command_topic: home-assistant/alarm/set
    code: !secret alarm_code
    pending_time: 45
    delay_time: 45
    trigger_time: 120
    disarmed:
      trigger_time: 0
    armed_home:
      pending_time: 0
      delay_time: 0
    armed_night:
      pending_time: 0
      delay_time: 0

################################################
## Automation
################################################

automation:
  - alias: persistence_subscribe_alarm_control_panel
    initial_state: 'on'
    hide_entity: true
    trigger:
      - platform: mqtt
        topic: home-assistant/alarm
    condition:
      - condition: template
        value_template: "{{ not is_state(alarm_control_panel.alarm_system, trigger.payload) }}"
    action:
      - service_template: >-
          {% if trigger.payload == 'armed_home' %}
            alarm_control_panel.alarm_arm_home
          {% elif trigger.payload == 'armed_night' %}
            alarm_control_panel.alarm_arm_night
          {% elif trigger.payload == 'disarmed' %}
            alarm_control_panel.alarm_disarm
          {% else %}
            alarm_control_panel.alarm_arm_away
          {% endif %}
        entity_id: alarm_control_panel.alarm_system
        data:
          code: !secret alarm_code

  - alias: trigger_alarm_on_motion
    trigger:
      - platform: state
        entity_id: binary_sensor.master_bedroom_motion_sensor
        from: 'off'
        to: 'on'
      - platform: state
        entity_id: binary_sensor.living_room_motion_sensor
        from: 'off'
        to: 'on'
    condition:
      - condition: state
        entity_id: alarm_control_panel.alarm_system
        state: 'armed_away'
    action:
      service: alarm_control_panel.alarm_trigger
      entity_id: alarm_control_panel.alarm_system
      data:
        code: !secret alarm_code

  - alias: alarm_triggered_notification
    trigger:
      - platform: state
        entity_id: alarm_control_panel.alarm_system
        to: 'triggered'
    action:
      - service: notify.sms
        data_template:
          message: 'ALARM TRIGGERED!!! {{ states.alarm_control_panel.alarm_system.attributes.changed_by }}'
          target:
            - !secret mobile_michael
