################################################################
## Packages / Batteries
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'batteries'

      expose: &expose
        <<: *customize
        homebridge_hidden: true

    ################################################
    ## Group
    ################################################

    group.batteries:
      <<: *customize
      friendly_name: "Batteries"

    ################################################
    ## Sensor
    ################################################

    sensor.guest_bedroom_closet_door_contact_battery:
      <<: *customize
      friendly_name: "Guest Bedroom Closet Door Battery Level"

    sensor.guest_bedroom_storage_door_contact_battery:
      <<: *customize
      friendly_name: "Guest Bedroom Storage Door Battery Level"

    sensor.guest_bedroom_smoke_and_carbon_monoxide_detector_battery:
      <<: *customize
      friendly_name: "Guest Bedroom Smoke Detector Battery Level"

    sensor.julias_closet_door_contact_battery:
      <<: *customize
      friendly_name: "Julia's Closet Door Battery Level"

    sensor.laundry_room_flood_sensor_battery:
      <<: *customize
      friendly_name: "Laundry Room Flood Sensor Battery Level"

    sensor.laundry_room_smoke_and_carbon_monoxide_detector_battery:
      <<: *customize
      friendly_name: "Laundry Room Smoke Detector Battery Level"

    sensor.living_room_motion_sensor_battery:
      <<: *customize
      friendly_name: "Living Room Motion Sensor Battery Level"

    sensor.master_bedroom_smoke_and_carbon_monoxide_detector_battery:
      <<: *customize
      friendly_name: "Master Bedroom Smoke Detector Battery Level"

    sensor.michaels_closet_door_contact_battery:
      <<: *customize
      friendly_name: "Michael's Closet Door Battery Level"

################################################
## Group
################################################

group:
  batteries:
    control: hidden
    entities:
      - sensor.wirelesstag_laundry_room_battery
      - sensor.wirelesstag_diamond_crown_humidor_battery
      - sensor.guest_bedroom_closet_door_contact_battery
      - sensor.guest_bedroom_storage_door_contact_battery
      - sensor.guest_bedroom_smoke_and_carbon_monoxide_detector_battery
      - sensor.julias_closet_door_contact_battery
      - sensor.julias_iphone_battery_level
      - sensor.laundry_room_flood_sensor_battery
      - sensor.laundry_room_smoke_and_carbon_monoxide_detector_battery
      - sensor.living_room_motion_sensor_battery
      - sensor.living_room_nest_protect_battery_health
      - sensor.master_bedroom_smoke_and_carbon_monoxide_detector_battery
      - sensor.michaels_closet_door_contact_battery
      - sensor.michaels_iphone_battery_level

################################################
## Sensor
################################################

sensor:
  - platform: template
    sensors:
      guest_bedroom_closet_door_contact_battery:
        entity_id: zwave.guest_bedroom_closet_door_contact
        value_template: "{{ (states.zwave.guest_bedroom_closet_door_contact.attributes|default).battery_level|default|int('unknown') }}"
        unit_of_measurement: '%'
        device_class: battery
        icon_template: >-
          {% set battery_level = states('sensor.guest_bedroom_closet_door_contact_battery')|int('unknown') %}
          {% if battery_level == 'unknown' %}
            mdi:battery-unknown
          {% else %}
            {% set battery_round = (battery_level|int / 10)|int * 10 %}
            {% if battery_round >= 100 %}
              mdi:battery
            {% elif battery_round > 0 %}
              mdi:battery-{{ battery_round }}
            {% else %}
              mdi:battery-alert
            {% endif %}
          {% endif %}

      guest_bedroom_storage_door_contact_battery:
        entity_id: zwave.guest_bedroom_storage_door_contact
        value_template: "{{ (states.zwave.guest_bedroom_storage_door_contact.attributes|default).battery_level|default|int('unknown') }}"
        unit_of_measurement: '%'
        device_class: battery
        icon_template: >-
          {% set battery_level = states('sensor.guest_bedroom_storage_door_contact_battery')|int('unknown') %}
          {% if battery_level == 'unknown' %}
            mdi:battery-unknown
          {% else %}
            {% set battery_round = (battery_level|int / 10)|int * 10 %}
            {% if battery_round >= 100 %}
              mdi:battery
            {% elif battery_round > 0 %}
              mdi:battery-{{ battery_round }}
            {% else %}
              mdi:battery-alert
            {% endif %}
          {% endif %}

      guest_bedroom_smoke_and_carbon_monoxide_detector_battery:
        entity_id: zwave.guest_bedroom_smoke_and_carbon_monoxide_detector
        value_template: "{{ (states.zwave.guest_bedroom_smoke_and_carbon_monoxide_detector.attributes|default).battery_level|default|int('unknown') }}"
        unit_of_measurement: '%'
        device_class: battery
        icon_template: >-
          {% set battery_level = states('sensor.guest_bedroom_smoke_and_carbon_monoxide_detector_battery')|int('unknown') %}
          {% if battery_level == 'unknown' %}
            mdi:battery-unknown
          {% else %}
            {% set battery_round = (battery_level|int / 10)|int * 10 %}
            {% if battery_round >= 100 %}
              mdi:battery
            {% elif battery_round > 0 %}
              mdi:battery-{{ battery_round }}
            {% else %}
              mdi:battery-alert
            {% endif %}
          {% endif %}

      julias_closet_door_contact_battery:
        entity_id: zwave.julias_closet_door_contact
        value_template: "{{ (states.zwave.julias_closet_door_contact.attributes|default).battery_level|default|int('unknown') }}"
        unit_of_measurement: '%'
        device_class: battery
        icon_template: >-
          {% set battery_level = states('sensor.julias_closet_door_contact_battery')|int('unknown') %}
          {% if battery_level == 'unknown' %}
            mdi:battery-unknown
          {% else %}
            {% set battery_round = (battery_level|int / 10)|int * 10 %}
            {% if battery_round >= 100 %}
              mdi:battery
            {% elif battery_round > 0 %}
              mdi:battery-{{ battery_round }}
            {% else %}
              mdi:battery-alert
            {% endif %}
          {% endif %}

      laundry_room_flood_sensor_battery:
        entity_id: zwave.laundry_room_flood_sensor
        value_template: "{{ (states.zwave.laundry_room_flood_sensor.attributes|default).battery_level|default|int('unknown') }}"
        unit_of_measurement: '%'
        device_class: battery
#        icon_template: >-
#          {% set battery_level = states('sensor.laundry_room_flood_sensor_battery')|int('unknown') %}
#          {% if battery_level == 'unknown' %}
#            mdi:battery-unknown
#          {% else %}
#            {% set battery_round = (battery_level|int / 10)|int * 10 %}
#            {% if battery_round >= 100 %}
#              mdi:battery
#            {% elif battery_round > 0 %}
#              mdi:battery-{{ battery_round }}
#            {% else %}
#              mdi:battery-alert
#            {% endif %}
#          {% endif %}

      laundry_room_smoke_and_carbon_monoxide_detector_battery:
        entity_id: zwave.laundry_room_smoke_and_carbon_monoxide_detector
        value_template: "{{ (states.zwave.laundry_room_smoke_and_carbon_monoxide_detector.attributes|default).battery_level|default|int('unknown') }}"
        unit_of_measurement: '%'
        device_class: battery
        icon_template: >-
          {% set battery_level = states('sensor.laundry_room_smoke_and_carbon_monoxide_detector_battery')|int('unknown') %}
          {% if battery_level == 'unknown' %}
            mdi:battery-unknown
          {% else %}
            {% set battery_round = (battery_level|int / 10)|int * 10 %}
            {% if battery_round >= 100 %}
              mdi:battery
            {% elif battery_round > 0 %}
              mdi:battery-{{ battery_round }}
            {% else %}
              mdi:battery-alert
            {% endif %}
          {% endif %}

      living_room_motion_sensor_battery:
        entity_id: zwave.living_room_motion_sensor
        value_template: "{{ (states.zwave.living_room_motion_sensor.attributes|default).battery_level|default|int('unknown') }}"
        unit_of_measurement: '%'
        device_class: battery
        icon_template: >-
          {% set battery_level = states('sensor.living_room_motion_sensor_battery')|int('unknown') %}
          {% if battery_level == 'unknown' %}
            mdi:battery-unknown
          {% else %}
            {% set battery_round = (battery_level|int / 10)|int * 10 %}
            {% if battery_round >= 100 %}
              mdi:battery
            {% elif battery_round > 0 %}
              mdi:battery-{{ battery_round }}
            {% else %}
              mdi:battery-alert
            {% endif %}
          {% endif %}

      master_bedroom_smoke_and_carbon_monoxide_detector_battery:
        entity_id: zwave.master_bedroom_smoke_and_carbon_monoxide_detector
        value_template: "{{ (states.zwave.master_bedroom_smoke_and_carbon_monoxide_detector.attributes|default).battery_level|default|int('unknown') }}"
        unit_of_measurement: '%'
        device_class: battery
        icon_template: >-
          {% set battery_level = states('sensor.master_bedroom_smoke_and_carbon_monoxide_detector_battery')|int('unknown') %}
          {% if battery_level == 'unknown' %}
            mdi:battery-unknown
          {% else %}
            {% set battery_round = (battery_level|int / 10)|int * 10 %}
            {% if battery_round >= 100 %}
              mdi:battery
            {% elif battery_round > 0 %}
              mdi:battery-{{ battery_round }}
            {% else %}
              mdi:battery-alert
            {% endif %}
          {% endif %}

      michaels_closet_door_contact_battery:
        entity_id: zwave.michaels_closet_door_contact
        value_template: "{{ (states.zwave.michaels_closet_door_contact.attributes|default).battery_level|default|int('unknown') }}"
        unit_of_measurement: '%'
        device_class: battery
        icon_template: >-
          {% set battery_level = states('sensor.michaels_closet_door_contact_battery')|int('unknown') %}
          {% if battery_level == 'unknown' %}
            mdi:battery-unknown
          {% else %}
            {% set battery_round = (battery_level|int / 10)|int * 10 %}
            {% if battery_round >= 100 %}
              mdi:battery
            {% elif battery_round > 0 %}
              mdi:battery-{{ battery_round }}
            {% else %}
              mdi:battery-alert
            {% endif %}
          {% endif %}
