################################################################
## Packages / Batteries
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'batteries'

      expose: &expose
        <<: *customize
        homebridge_hidden: true

    ################################################
    ## Group
    ################################################

    group.batteries:
      <<: *customize
      friendly_name: "Batteries"

    ################################################
    ## Sensor
    ################################################

    sensor.guest_bedroom_closet_door_contact_battery:
      <<: *customize
      friendly_name: "Guest Bedroom Closet Door"

    sensor.guest_bedroom_storage_door_contact_battery:
      <<: *customize
      friendly_name: "Guest Bedroom Storage Door"

    sensor.guest_bedroom_smoke_and_carbon_monoxide_detector_battery:
      <<: *customize
      friendly_name: "Guest Bedroom Smoke Detector"

    sensor.julias_closet_door_contact_battery:
      <<: *customize
      friendly_name: "Julia's Closet Door"

    sensor.julias_iphone_battery:
      <<: *expose
      friendly_name: "Julia's iPhone"

    sensor.laundry_room_flood_sensor_battery:
      <<: *customize
      friendly_name: "Laundry Room Flood Sensor"

    sensor.living_room_motion_sensor_battery:
      <<: *customize
      friendly_name: "Living Room Motion Sensor"

    sensor.master_bedroom_smoke_and_carbon_monoxide_detector_battery:
      <<: *customize
      friendly_name: "Master Bedroom Smoke Detector"

    sensor.michaels_closet_door_contact_battery:
      <<: *customize
      friendly_name: "Michael's Closet Door"

    sensor.michaels_iphone_battery:
      <<: *expose
      friendly_name: "Michael's iPhone"

################################################
## Group
################################################

group:
  batteries:
    control: hidden
    entities:
      - guest_bedroom_closet_door_contact_battery
      - guest_bedroom_storage_door_contact_battery
      - guest_bedroom_smoke_and_carbon_monoxide_detector_battery
      - julias_closet_door_contact_battery
      - julias_iphone_battery
      - laundry_room_flood_sensor_battery
      - living_room_motion_sensor_battery
      - master_bedroom_smoke_and_carbon_monoxide_detector_battery
      - michaels_closet_door_contact_battery
      - michaels_iphone_battery

################################################
## Sensor
################################################

sensor:
  - platform: template
    sensors:
      guest_bedroom_closet_door_contact_battery:
        entity_id: zwave.guest_bedroom_closet_door_contact
        value_template: "{{ (states.zwave.guest_bedroom_closet_door_contact.attributes|default).battery_level|default|int('unknown') }}"
        unit_of_measurement: '%'
        icon_template: >-
          {% set battery_level = states('sensor.guest_bedroom_closet_door_contact_battery')|int('unknown') %}
          {% if battery_level == 'unknown' %}
            mdi:battery-unknown
          {% else %}
            {% set battery_round = (battery_level|int / 10)|int * 10 %}
            {% if battery_round >= 100 %}
              mdi:battery
            {% elif battery_round > 0 %}
              mdi:battery-{{ battery_round }}
            {% else %}
              mdi:battery-alert
            {% endif %}
          {% endif %}

      guest_bedroom_storage_door_contact_battery:
        entity_id: zwave.guest_bedroom_storage_door_contact
        value_template: "{{ (states.zwave.guest_bedroom_storage_door_contact.attributes|default).battery_level|default|int('unknown') }}"
        unit_of_measurement: '%'
        icon_template: >-
          {% set battery_level = states('sensor.guest_bedroom_storage_door_contact_battery')|int('unknown') %}
          {% if battery_level == 'unknown' %}
            mdi:battery-unknown
          {% else %}
            {% set battery_round = (battery_level|int / 10)|int * 10 %}
            {% if battery_round >= 100 %}
              mdi:battery
            {% elif battery_round > 0 %}
              mdi:battery-{{ battery_round }}
            {% else %}
              mdi:battery-alert
            {% endif %}
          {% endif %}

      guest_bedroom_smoke_and_carbon_monoxide_detector_battery:
        entity_id: zwave.guest_bedroom_smoke_and_carbon_monoxide_detector
        value_template: "{{ (states.zwave.guest_bedroom_smoke_and_carbon_monoxide_detector.attributes|default).battery_level|default|int('unknown') }}"
        unit_of_measurement: '%'
        icon_template: >-
          {% set battery_level = states('sensor.guest_bedroom_smoke_and_carbon_monoxide_detector_battery')|int('unknown') %}
          {% if battery_level == 'unknown' %}
            mdi:battery-unknown
          {% else %}
            {% set battery_round = (battery_level|int / 10)|int * 10 %}
            {% if battery_round >= 100 %}
              mdi:battery
            {% elif battery_round > 0 %}
              mdi:battery-{{ battery_round }}
            {% else %}
              mdi:battery-alert
            {% endif %}
          {% endif %}

      julias_closet_door_contact_battery:
        entity_id: zwave.julias_closet_door_contact
        value_template: "{{ (states.zwave.julias_closet_door_contact.attributes|default).battery_level|default|int('unknown') }}"
        unit_of_measurement: '%'
        icon_template: >-
          {% set battery_level = states('sensor.julias_closet_door_contact_battery')|int('unknown') %}
          {% if battery_level == 'unknown' %}
            mdi:battery-unknown
          {% else %}
            {% set battery_round = (battery_level|int / 10)|int * 10 %}
            {% if battery_round >= 100 %}
              mdi:battery
            {% elif battery_round > 0 %}
              mdi:battery-{{ battery_round }}
            {% else %}
              mdi:battery-alert
            {% endif %}
          {% endif %}

      julias_iphone_battery:
        entity_id: device_tracker.julias_iphone
        value_template: "{{ (states.device_tracker.julias_iphone.attributes|default).battery|default|int('unknown') }}"
        unit_of_measurement: '%'
        icon_template: >-
          {% set battery_state = states('sensor.julias_iphone_battery_state')|lower %}
          {% set battery_level = states('sensor.julias_iphone_battery_level')|int('unknown') %}
          {% set battery_round = (battery_level|int / 10)|int * 10 %}

          {% if battery_level == 'unknown' %}
            mdi:battery-unknown
          {% elif battery_state == 'charging' %}
            {% if battery_round < 20 %}
              {% set battery_round = 20 %}
            {% elif battery_round == 50 %}
              {% set battery_round = 60 %}
            {% elif battery_round == 70 %}
              {% set battery_round = 80 %}
            {% endif %}

            mdi:battery-charging-{{ battery_round }}
          {% else %}
            {% if battery_round >= 100 %}
              mdi:battery
            {% elif battery_round > 0 %}
              mdi:battery-{{ battery_round }}
            {% else %}
              mdi:battery-alert
            {% endif %}
          {% endif %}

      laundry_room_flood_sensor_battery:
        entity_id: zwave.laundry_room_flood_sensor
        value_template: "{{ (states.zwave.laundry_room_flood_sensor.attributes|default).battery_level|default|int('unknown') }}"
        unit_of_measurement: '%'
        icon_template: >-
          {% set battery_level = states('sensor.laundry_room_flood_sensor_battery')|int('unknown') %}
          {% if battery_level == 'unknown' %}
            mdi:battery-unknown
          {% else %}
            {% set battery_round = (battery_level|int / 10)|int * 10 %}
            {% if battery_round >= 100 %}
              mdi:battery
            {% elif battery_round > 0 %}
              mdi:battery-{{ battery_round }}
            {% else %}
              mdi:battery-alert
            {% endif %}
          {% endif %}

      living_room_motion_sensor_battery:
        entity_id: zwave.living_room_motion_sensor
        value_template: "{{ (states.zwave.living_room_motion_sensor.attributes|default).battery_level|default|int('unknown') }}"
        unit_of_measurement: '%'
        icon_template: >-
          {% set battery_level = states('sensor.living_room_motion_sensor_battery')|int('unknown') %}
          {% if battery_level == 'unknown' %}
            mdi:battery-unknown
          {% else %}
            {% set battery_round = (battery_level|int / 10)|int * 10 %}
            {% if battery_round >= 100 %}
              mdi:battery
            {% elif battery_round > 0 %}
              mdi:battery-{{ battery_round }}
            {% else %}
              mdi:battery-alert
            {% endif %}
          {% endif %}

      master_bedroom_smoke_and_carbon_monoxide_detector_battery:
        entity_id: zwave.master_bedroom_smoke_and_carbon_monoxide_detector
        value_template: "{{ (states.zwave.master_bedroom_smoke_and_carbon_monoxide_detector.attributes|default).battery_level|default|int('unknown') }}"
        unit_of_measurement: '%'
        icon_template: >-
          {% set battery_level = states('sensor.master_bedroom_smoke_and_carbon_monoxide_detector_battery')|int('unknown') %}
          {% if battery_level == 'unknown' %}
            mdi:battery-unknown
          {% else %}
            {% set battery_round = (battery_level|int / 10)|int * 10 %}
            {% if battery_round >= 100 %}
              mdi:battery
            {% elif battery_round > 0 %}
              mdi:battery-{{ battery_round }}
            {% else %}
              mdi:battery-alert
            {% endif %}
          {% endif %}

      michaels_closet_door_contact_battery:
        entity_id: zwave.michaels_closet_door_contact
        value_template: "{{ (states.zwave.michaels_closet_door_contact.attributes|default).battery_level|default|int('unknown') }}"
        unit_of_measurement: '%'
        icon_template: >-
          {% set battery_level = states('sensor.michaels_closet_door_contact_battery')|int('unknown') %}
          {% if battery_level == 'unknown' %}
            mdi:battery-unknown
          {% else %}
            {% set battery_round = (battery_level|int / 10)|int * 10 %}
            {% if battery_round >= 100 %}
              mdi:battery
            {% elif battery_round > 0 %}
              mdi:battery-{{ battery_round }}
            {% else %}
              mdi:battery-alert
            {% endif %}
          {% endif %}

      michaels_iphone_battery:
        entity_id: device_tracker.michaels_iphone
        value_template: "{{ (states.device_tracker.michaels_iphone.attributes|default).battery|default|int('unknown') }}"
        unit_of_measurement: '%'
        icon_template: >-
          {% set battery_state = states('sensor.michaels_iphone_battery_state')|lower %}
          {% set battery_level = states('sensor.michaels_iphone_battery_level')|int('unknown') %}
          {% set battery_round = (battery_level|int / 10)|int * 10 %}

          {% if battery_level == 'unknown' %}
            mdi:battery-unknown
          {% elif battery_state == 'charging' %}
            {% if battery_round < 20 %}
              {% set battery_round = 20 %}
            {% elif battery_round == 50 %}
              {% set battery_round = 60 %}
            {% elif battery_round == 70 %}
              {% set battery_round = 80 %}
            {% endif %}

            mdi:battery-charging-{{ battery_round }}
          {% else %}
            {% if battery_round >= 100 %}
              mdi:battery
            {% elif battery_round > 0 %}
              mdi:battery-{{ battery_round }}
            {% else %}
              mdi:battery-alert
            {% endif %}
          {% endif %}
