################################################################
## Packages / Cloud
## https://www.home-assistant.io/components/cloud/
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'cloud'

################################################
## Cloud
################################################

cloud:
  alexa:
    filter:
      include_entities:
        - automation.master_bedroom_motion
        - automation.living_room_motion
      exclude_domains:
        - group
        - automation
        - alert
      exclude_entities:
        - switch.raspberry_pi
        - switch.pc
        - switch.imac
        - sensor.wirelesstag_laundry_room_temperature
        - sensor.wirelesstag_diamond_crown_humidor_temperature
        - sensor.dark_sky_temperature
    entity_config:
      sensor.living_room_motion_sensor_temperature:
        name: Living Room Temperature
        display_categories: TEMPERATURE_SENSOR
      sensor.master_bedroom_motion_sensor_temperature:
        name: Bedroom Temperature
        display_categories: TEMPERATURE_SENSOR
      sensor.laundry_room_flood_sensor_temperature:
        name: Laundry Room Temperature
        display_categories: TEMPERATURE_SENSOR
      switch.living_room_bookshelf_lamp:
        display_categories: LIGHT
