################################################################
## Packages / Good Morning/Night
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'good_morning_night'

    ################################################
    ## Script
    ################################################

    script.good_morning:
      <<: *customize
      friendly_name: "Good Morning"
      icon: mdi:weather-sunny

    script.good_night:
      <<: *customize
      friendly_name: "Good Night"
      icon: mdi:weather-night

################################################
## Automation
################################################

automation:
  - alias: auto_evening
    trigger:
      platform: sun
      event: sunset
      offset: "-00:30:00"
    condition:
      condition: state
      entity_id: sensor.house_mode
      state: 'home'
    action:
      service: script.good_evening

  - alias: auto_night
    trigger:
      platform: time
      at: "23:30:00"
    condition:
      condition: state
      entity_id: sensor.house_mode
      state: 'home'
    action:
      service: script.good_evening

################################################
## Script
################################################

script:
  good_evening:
    sequence:
      - service: automation.turn_on
        data:
          entity_id:
            - automation.living_room_motion
            - automation.master_bedroom_motion

#      - service: script.light_control
#        data:
#          entity_id: light.master_bedroom
#          state: 'on'
#          brightness: 255
#          color_temp: 370
#          transition: 5

  good_night:
    sequence:
      - service: automation.turn_off
        data:
          entity_id:
            - automation.living_room_motion
            - automation.master_bedroom_motion

      - service: script.light_control
        data:
          entity_id: group.all_lights
          state: 'off'
          transition: 5
