################################################################
## Packages / Good Morning/Night
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'good_morning_night'

    ################################################
    ## Automation
    ################################################

    automation.auto_morning:
      <<: *customize
      friendly_name: "Auto Morning"
      icon: mdi:robot

    automation.auto_evening:
      <<: *customize
      friendly_name: "Auto Evening"
      icon: mdi:robot

    automation.auto_night:
      <<: *customize
      friendly_name: "Auto Night"
      icon: mdi:robot

    ################################################
    ## Script
    ################################################

    script.good_evening:
      <<: *customize
      friendly_name: "Good Evening"
      icon: mdi:weather-sunset

    script.good_night:
      <<: *customize
      friendly_name: "Good Night"
      icon: mdi:weather-night

################################################
## Automation
################################################

automation:
  - alias: auto_morning
    initial_state: true
    trigger:
      - platform: sun
        event: sunrise
        offset: '-00:30:00'
    condition:
      - condition: state
        entity_id: alarm_control_panel.alarm_system
        state: 'armed_night'
    action:
      - service: alarm_control_panel.alarm_arm_home
        entity_id: alarm_control_panel.alarm_system
        data:
          code: !secret alarm_code

  - alias: auto_evening
    trigger:
      - platform: sun
        event: sunset
        offset: '-00:30:00'
      - platform: state
        entity_id: alarm_control_panel.alarm_system
        to: 'armed_home'
    condition:
      condition: and
      conditions:
        - condition: sun
          after: sunset
          after_offset: '-00:30:00'
        - condition: or
          conditions:
            - condition: state
              entity_id: alarm_control_panel.alarm_system
              state: 'armed_home'
            - condition: state
              entity_id: alarm_control_panel.alarm_system
              state: 'disarmed'
    action:
      - service: script.good_evening

  - alias: auto_night
    trigger:
      - platform: time
        at: '23:30:00'
    condition:
      condition: and
      conditions: 
        - condition: time
          weekday:
            - mon
            - tue
            - wed
            - thu
            - sun
        - condition: state
          entity_id: alarm_control_panel.alarm_system
          state: 'armed_home'
    action:
      - service: alarm_control_panel.alarm_arm_night
        entity_id: alarm_control_panel.alarm_system
        data:
          code: !secret alarm_code

  - alias: manual_night
    trigger:
      - platform: state
        entity_id: alarm_control_panel.alarm_system
        to: 'armed_night'
        from: 'armed_home'
      - platform: state
        entity_id: alarm_control_panel.alarm_system
        to: 'armed_night'
        from: 'disarmed'
    action:
      - service: script.good_night

################################################
## Script
################################################

script:
  good_evening:
    sequence:
      - service: automation.turn_on
        data:
          entity_id:
            - automation.living_room_motion
            - automation.master_bedroom_motion

  good_night:
    sequence:
      - service: automation.turn_off
        data:
          entity_id:
            - automation.living_room_motion
            - automation.master_bedroom_motion

      - service: script.all_lights_off
