################################################################
## Packages / Harmony
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'harmony'

    ################################################
    ## Remote
    ################################################

    remote.living_room:
      <<: *customize
      icon: mdi:remote

    remote.basement:
      <<: *customize
      icon: mdi:remote

################################################
## Harmony
################################################

# https://www.home-assistant.io/components/remote.harmony/
remote:
  - platform: harmony
    name: Living Room
    host: 192.168.0.10
    activity: Watch TV

  - platform: harmony
    name: Basement
    host: 192.168.0.18
    activity: Watch TV
