################################################################
## Packages / Homekit
## https://www.home-assistant.io/components/homekit/
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'homekit'

################################################
## Automation
################################################

automation:
  - alias: 'Start HomeKit'
    trigger:
      - platform: event
        event_type: zwave.network_ready
      - platform: event
        event_type: zwave.network_complete
    action:
      - service: homekit.start

################################################
## Homekit
################################################

homekit:
  auto_start: false
  filter:
    exclude_domains:
      - automation
      - device_tracker
      - sensor
      - script
      - remote
    exclude_entities:
      - binary_sensor.living_room_nest_protect_online
      - binary_sensor.living_room_thermostat_fan
      - binary_sensor.living_room_thermostat_has_leaf
      - binary_sensor.living_room_thermostat_is_locked
      - binary_sensor.living_room_thermostat_is_using_emergency_heat
      - binary_sensor.living_room_thermostat_online
      - binary_sensor.otter_den_away
      - light.dresser_lamp
      - light.nightstand_lamp
      - light.julias_closet
      - light.michaels_closet
      - light.table_light
      - light.dining_room_spot
      - light.guest_bedroom_storage
      - switch.aeotec_zstick_disco_light
      - switch.raspberry_pi
      - switch.pc
      - switch.imac
    include_entities:
      - automation.master_bedroom_motion
      - automation.living_room_motion
    entity_config:
      alarm_control_panel.alarm_system:
        code: !secret alarm_code
