################################################################
## Packages / House Mode
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'house_mode'

      expose: &expose
        <<: *customize
        homebridge_hidden: false

    ################################################
    ## Automation
    ################################################

    automation.auto_away:
      <<: *customize
      friendly_name: "Auto Away"
      icon: mdi:robot

    automation.auto_home:
      <<: *customize
      friendly_name: "Auto Away"
      icon: mdi:robot

    ################################################
    ## Group
    ################################################

    group.house_mode:
      <<: *customize
      friendly_name: "House Mode"
      icon: mdi:home-variant

    ################################################
    ## Input Boolean
    ################################################

    input_boolean.guest_mode:
      <<: *customize
      friendly_name: "Guest Mode"
      icon: mdi:account

    input_boolean.night_mode:
      <<: *customize
      friendly_name: "Night Mode"
      icon: mdi:weather-night

    ################################################
    ## Sensor
    ################################################

    sensor.house_mode:
      <<: *customize
      friendly_name: "House Mode"

################################################
## Group
################################################

group:
  house_mode:
    control: hidden
    entities:
      - sensor.house_mode
      - input_boolean.night_mode
      - input_boolean.guest_mode
      - sensor.household

################################################
## Input Boolean
################################################

input_boolean:
  guest_mode:

  night_mode:

################################################
## Sensor
################################################

sensor:
  - platform: template
    sensors:
      house_mode:
        entity_id:
          - input_boolean.guest_mode
          - input_boolean.night_mode
          - sensor.household
        value_template: >-
          {% if is_state('input_boolean.guest_mode', 'on') %}
            Guest
          {% elif is_state('sensor.household', 'Home') or is_state('sensor.household', 'Arriving') or is_state('sensor.household', 'Departing') %}
            {% if is_state('input_boolean.night_mode', 'on') %}
              Night
            {% else %}
              Home
            {% endif %}
          {% elif is_state('sensor.household', 'Vacation') %}
            Vacation
          {% else %}
            Away
          {% endif %}
        icon_template: >-
          {% set mode = states('sensor.house_mode') %}
          {% if mode == 'Guest' %}
            mdi:account
          {% elif mode == 'Home' %}
            mdi:home
          {% elif mode == 'Night' %}
            mdi:weather-night
          {% elif mode == 'Vacation' %}
            mdi:beach
          {% else %}
            mdi:home-outline
          {% endif %}

################################################
## Automation
################################################

automation:
  - alias: auto_away
    trigger:
      - platform: state
        entity_id: sensor.house_mode
        to:
          - 'Away'
          - 'Vacation'
    action:
      - service: script.light_control
        data:
          entity_id: group.all_lights
          state: 'off'
          transition: 5
      - service: switch.turn_off
        data:
          entity_id: switch.living_room_bookshelf_lamp
      - service: nest.set_mode
        data:
          home_mode: away

  - alias: auto_home
    trigger:
      - platform: state
        entity_id: sensor.house_mode
        from:
          - 'Away'
          - 'Vacation'
        to: 'Home'
    action:
      - service: nest.set_mode
        data:
          home_mode: home
