################################################################
## Packages / House Mode
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'house_mode'

      expose: &expose
        <<: *customize
        homebridge_hidden: false

    ################################################
    ## Group
    ################################################

    group.house_mode:
      <<: *customize
      friendly_name: "House Mode"
      icon: mdi:home-variant

    ################################################
    ## Input Boolean
    ################################################

    input_boolean.guest_mode:
      <<: *customize
      friendly_name: "Guest Mode"
      icon: mdi:account

    input_boolean.night_mode:
      <<: *customize
      friendly_name: "Night Mode"
      icon: mdi:weather-night

    input_boolean.vacation_mode:
      <<: *customize
      friendly_name: "Vacation Mode"
      icon: mdi:beach

    ################################################
    ## Sensor
    ################################################

    sensor.household:
      <<: *customize
      friendly_name: "Household"

    sensor.house_mode:
      <<: *customize
      friendly_name: "House Mode"

################################################
## Group
################################################

group:
  house_mode:
    control: hidden
    entities:
      - sensor.house_mode
      - input_boolean.night_mode
      - input_boolean.guest_mode
      - input_boolean.vacation_mode
      - sensor.household

################################################
## Input Boolean
################################################

input_boolean:
  guest_mode:

  night_mode:

  vacation_mode:

################################################
## Sensor
################################################

sensor:
  - platform: template
    sensors:
      household:
        entity_id: group.all_devices
        value_template: >-
          {% if is_state('group.all_devices', 'home') %}
            home
          {% else %}
            away
          {% endif %}
        icon_template: >-
          {% if is_state('group.all_devices', 'home') %}
            mdi:home
          {% else %}
            mdi:home-outline
          {% endif %}

      house_mode:
        entity_id:
          - input_boolean.guest_mode
          - input_boolean.night_mode
          - input_boolean.vacation_mode
          - sensor.household
        value_template: >-
          {% if is_state('input_boolean.guest_mode', 'on') %}
            guest
          {% elif is_state('input_boolean.night_mode', 'on') %}
            night
          {% elif is_state('sensor.household', 'home') %}
            home
          {% elif is_state('input_boolean.vacation_mode', 'on') %}
            vacation
          {% else %}
            away
          {% endif %}
        icon_template: >-
          {% if is_state('input_boolean.guest_mode', 'on') %}
            mdi:account
          {% elif is_state('input_boolean.night_mode', 'on') %}
            mdi:weather-night
          {% elif is_state('sensor.household', 'home') %}
            mdi:home
          {% elif is_state('input_boolean.vacation_mode', 'on') %}
            mdi:beach
          {% else %}
            mdi:home-outline
          {% endif %}
