################################################################
## Packages / House Mode
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'house_mode'

      expose: &expose
        <<: *customize
        homebridge_hidden: false

    ################################################
    ## Automation
    ################################################

    automation.auto_away:
      <<: *customize
      friendly_name: "Auto Away"
      icon: mdi:robot

    automation.auto_home:
      <<: *customize
      friendly_name: "Auto Home"
      icon: mdi:robot

    ################################################
    ## Binary Sensor
    ################################################

    binary_sensor.living_room_motion_last_30:
      <<: *customize
      friendly_name: "Motion in Living Room in Last 30 Minutes"

    binary_sensor.master_bedroom_motion_last_30:
      <<: *customize
      friendly_name: "Motion in Master Bedroom in Last 30 Minutes"

    ################################################
    ## Group
    ################################################

    group.house_mode:
      <<: *customize
      friendly_name: "House Mode"
      icon: mdi:home-variant

    ################################################
    ## Input Boolean
    ################################################

    input_boolean.guest_mode:
      <<: *customize
      friendly_name: "Guest Mode"
      icon: mdi:account

    input_boolean.night_mode:
      <<: *customize
      friendly_name: "Night Mode"
      icon: mdi:weather-night

    ################################################
    ## Script
    ################################################

    script.all_lights_off:
      <<: *customize
      friendly_name: Turn All Lights Off

    ################################################
    ## Sensor
    ################################################

    sensor.house_mode:
      <<: *customize
      friendly_name: "House Mode"

################################################
## Group
################################################

group:
  house_mode:
    control: hidden
    entities:
      - sensor.house_mode
      - input_boolean.night_mode
      - input_boolean.guest_mode
      - sensor.household

################################################
## Input Boolean
################################################

input_boolean:
  guest_mode:

  night_mode:

################################################
## Sensor
################################################

sensor:
  - platform: template
    sensors:
      house_mode:
        entity_id:
          - input_boolean.guest_mode
          - input_boolean.night_mode
          - sensor.household
        value_template: >-
          {% if is_state('input_boolean.guest_mode', 'on') %}
            Guest
          {% elif is_state('sensor.household', 'Home') or is_state('sensor.household', 'Arriving') or is_state('sensor.household', 'Departing') %}
            {% if is_state('input_boolean.night_mode', 'on') %}
              Night
            {% else %}
              Home
            {% endif %}
          {% elif is_state('sensor.household', 'Vacation') %}
            Vacation
          {% else %}
            Away
          {% endif %}
        icon_template: >-
          {% set mode = states('sensor.house_mode') %}
          {% if mode == 'Guest' %}
            mdi:account
          {% elif mode == 'Home' %}
            mdi:home
          {% elif mode == 'Night' %}
            mdi:weather-night
          {% elif mode == 'Vacation' %}
            mdi:beach
          {% else %}
            mdi:home-outline
          {% endif %}

################################################
## Automation
################################################

automation:
  - alias: auto_away
    trigger:
      - platform: state
        entity_id: sensor.household
        to: 'Away'
      - platform: state
        entity_id: sensor.household
        to: 'Vacation'
    condition:
      - condition: state
        entity_id: alarm_control_panel.alarm_system
        state: 'armed_home'
    action:
      - service: alarm_control_panel.alarm_arm_away
        entity_id: alarm_control_panel.alarm_system
        data:
          code: !secret alarm_code
      - service: script.all_lights_off
      - service: script.set_nest_away

  - alias: auto_home
    trigger:
      - platform: state
        entity_id: sensor.household
        to: 'Arriving'
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: "{{ trigger.from_state.state == 'Away' or trigger.from_state.state == 'Vacation' }}"
        - condition: template
          value_template: "{{ not is_state('alarm_control_panel.alarm_system', 'armed_home') and not is_state('alarm_control_panel.alarm_system', 'disarmed') }}"
    action:
      - service: alarm_control_panel.alarm_arm_home
        entity_id: alarm_control_panel.alarm_system
        data:
          code: !secret alarm_code
      - service: script.set_nest_home

################################################
## Binary Sensor
################################################

binary_sensor:
  - platform: template
    sensors:
      living_room_motion_last_30:
        value_template: '{{ (as_timestamp(now())-as_timestamp(states.binary_sensor.living_room_motion_sensor.last_changed)) < 1800 }}'
        device_class: motion
      master_bedroom_motion_last_30:
        value_template: '{{ (as_timestamp(now())-as_timestamp(states.binary_sensor.master_bedroom_motion_sensor.last_changed)) < 1800 }}'
        device_class: motion
  - platform: 'bayesian'
    name: 'sleeping'
    prior: 0.33
    probability_threshold: 0.95
    observations:
      - entity_id: 'group.all_lights'
        prob_given_true: 1 # 100% chance that if sleeping all lights off
        prob_given_false: 0.80 # 80% chance that if not sleeping all lights off
        platform: 'state'
        to_state: 'off'
      - entity_id: 'sensor.household'
        prob_given_true: 1 # 100% chance that if sleeping home
        prob_given_false: 0.55 # 55% chance that if not sleeping home
        platform: 'state'
        to_state: 'Home'
      - entity_id: 'media_player.living_room_tv'
        prob_given_true: 1 # 100% chance if sleeping that tv off
        prob_given_false: 0.88 # 88% chance if not sleeping tv off
        platform: 'state'
        to_state: 'off'
      - entity_id: 'sensor.living_room_motion_last_30'
        prob_given_true: 0.99 # if sleeping 99% chance no living room motion
        prob_given_false: 0.8 # if not sleeping 80% chance no living room motion
        platform: 'state'
        to_state: 'Clear'
      - entity_id: 'master_bedroom_motion_last_30'
        prob_given_true: 0.5
        platform: 'state'
        to_state: 'Motion'
      - entity_id: 'sun.sun'
        prob_given_true: 0.7
        platform: 'state'
        to_state: 'below_horizon'

################################################
## Script
################################################

script:
  all_lights_off:
    sequence:
      - service: script.light_control
        data:
          entity_id: group.all_lights
          state: 'off'
          transition: 5
      - service: switch.turn_off
        data:
          entity_id: switch.basement_task_light
