################################################################
## Packages / HTTP
## https://home-assistant.io/components/http/
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'http'

################################################
## HTTP
################################################

http:
  api_password: !secret ha_password
  base_url: !secret ha_url
  cors_allowed_origins:
      - https://google.com
      - https://www.home-assistant.io
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - ::1
    - 192.168.1.7
  trusted_networks:
    - 127.0.0.1
    - ::1
    - 192.168.1.0/24
    - fd00::/8
  ip_ban_enabled: true
  login_attempts_threshold: 5
