################################################################
## Packages / Network Devices
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'network_devices'

      expose: &expose
        <<: *customize
        homebridge_hidden: false

    ################################################
    ## Group
    ################################################

    group.network_devices:
      <<: *customize
      friendly_name: "Network Devices"

    ################################################
    ## Switch
    ################################################

    switch.imac:
      <<: *customize
      friendly_name: 'iMac'
      icon: mdi:desktop-mac

    switch.raspberry_pi:
      <<: *customize
      friendly_name: 'Raspberry Pi'
      icon: mdi:raspberrypi

    switch.pc:
      <<: *customize
      friendly_name: 'PC'
      icon: mdi:desktop-tower

    ################################################
    ## Weblink
    ################################################

    weblink.router_admin:
      <<: *customize
      friendly_name: 'Router Admin'
      icon: mdi:router-wireless

    weblink.switch_admin:
      <<: *customize
      friendly_name: 'Switch Admin'
      icon: mdi:switch

    weblink.wifi_admin:
      <<: *customize
      friendly_name: 'Wifi Admin'
      icon: mdi:wifi

################################################
## Group
################################################

group:
  network_devices:
    control: hidden
    entities:
      - switch.imac
      - switch.raspberry_pi
      - switch.pc
      - weblink.router_admin
      - weblink.switch_admin
      - weblink.wifi_admin

################################################
## Switch
################################################

switch:
  # https://home-assistant.io/components/switch.wake_on_lan/
  - platform: wake_on_lan
    mac_address: 'D8:30:62:51:F6:6A'
    name: iMac
    host: '192.168.0.15'

  - platform: wake_on_lan
    mac_address: 'B8:27:EB:AA:44:B2'
    name: 'Raspberry Pi'
    host: '192.168.0.5'

  - platform: wake_on_lan
    mac_address: '10:DA:43:24:2B:A7'
    name: 'PC'
    host: '192.168.0.6'

################################################
## Weblinks
################################################

weblink:
  entities:
    - name: router_admin
      url: http://192.168.0.1
    - name: switch_admin
      url: http://192.168.0.2
    - name: wifi_admin
      url: http://192.168.0.3
