################################################################
## Packages / Presence
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'presence'

      expose: &expose
        <<: *customize
        homebridge_hidden: true

    ################################################
    ## Automation
    ################################################

    automation.person_arriving:
      <<: *expose
      friendly_name: "Mark person as just arrived"
      icon: mdi:map-marker

    automation.person_home:
      <<: *expose
      friendly_name: "Mark person as home"
      icon: mdi:map-marker

    automation.person_departing:
      <<: *expose
      friendly_name: "Mark person as just left"
      icon: mdi:map-marker

    automation.person_away:
      <<: *expose
      friendly_name: "Mark person as away"
      icon: mdi:map-marker

    automation.person_vacation:
      <<: *expose
      friendly_name: "Mark person as extended away"
      icon: mdi:map-marker

    ################################################
    ## Device Tracker
    ################################################

    device_tracker.julias_iphone:
      <<: *customize
      status_select: input_select.julias_status

    device_tracker.michaels_iphone:
      <<: *customize
      status_select: input_select.michaels_status

    ################################################
    ## Input Select
    ################################################

    input_select.julias_status:
      <<: *customize
      friendly_name: "Julia"
      entity_picture: /local/img/julia.jpg

    input_select.michaels_status:
      <<: *customize
      friendly_name: "Michael"
      entity_picture: /local/img/michael.jpg

    ################################################
    ## Sensor
    ################################################

    sensor.household:
      <<: *customize
      friendly_name: "Household"

################################################
## Input Select
################################################

input_select:
  julias_status:
    options:
      - Home
      - Arriving
      - Departing
      - Away
      - Vacation

  michaels_status:
    options:
      - Home
      - Arriving
      - Departing
      - Away
      - Vacation

################################################
## Sensor
################################################

sensor:
  - platform: template
    sensors:
      household:
        entity_id:
          - input_select.julias_status
          - input_select.michaels_status
        value_template: >-
          {% if is_state('input_select.julias_status', 'Home') or is_state('input_select.michaels_status', 'Home') %}
            Home
          {% elif is_state('input_select.julias_status', 'Arriving') or is_state('input_select.michaels_status', 'Arriving') %}
            Arriving
          {% elif is_state('input_select.julias_status', 'Departing') or is_state('input_select.michaels_status', 'Departing') %}
            Departing
          {% elif is_state('input_select.julias_status', 'Vacation') and is_state('input_select.michaels_status', 'Vacation') %}
            Vacation
          {% else %}
            Away
          {% endif %}
        icon_template: >-
          {% set household_status = states('sensor.household') %}
          {% if household_status == 'Home' or household_status == 'Arriving' %}
            mdi:map-marker-radius
          {% elif household_status == 'Vacation' %}
            mdi:beach
          {% else %}
            mdi:car
          {% endif %}

################################################
## Automation
################################################

automation:
  - alias: person_arriving
    hide_entity: true
    initial_state: true
    trigger:
      - platform: state
        entity_id: device_tracker.julias_iphone
        from: 'not_home'
        to: 'home'
      - platform: state
        entity_id: device_tracker.michaels_iphone
        from: 'not_home'
        to: 'home'
    action:
      - service: input_select.select_option
        data_template:
          entity_id: "{{ state_attr(trigger.entity_id, 'status_select') }}"
          option: >-
            {% if is_state(state_attr(trigger.entity_id, 'status_select'), 'Departing') %}
              Home
            {% else %}
              Arriving
            {% endif %}
 
  - alias: person_home
    hide_entity: true
    initial_state: true
    trigger:
      - platform: state
        entity_id: input_select.julias_status
        to: 'Arriving'
        for:
          minutes: 10
      - platform: state
        entity_id: input_select.michaels_status
        to: 'Arriving'
        for:
          minutes: 10
    action:
      - service: input_select.select_option
        data_template:
          entity_id: '{{ trigger.entity_id }}'
          option: 'Home'
 
  - alias: person_departing
    hide_entity: true
    initial_state: true
    trigger:
      - platform: state
        entity_id: device_tracker.julias_iphone
        from: 'home'
        to: 'not_home'
      - platform: state
        entity_id: device_tracker.michaels_iphone
        from: 'home'
        to: 'not_home'
    action:
      - service: input_select.select_option
        data_template:
          entity_id: "{{ state_attr(trigger.entity_id, 'status_select') }}"
          option: 'Departing'
 
  - alias: person_away
    hide_entity: true
    initial_state: true
    trigger:
      - platform: state
        entity_id: input_select.julias_status
        to: 'Departing'
        for:
          minutes: 10
      - platform: state
        entity_id: input_select.michaels_status
        to: 'Departing'
        for:
          minutes: 10
    action:
      - service: input_select.select_option
        data_template:
          entity_id: '{{ trigger.entity_id }}'
          option: 'Away'
 
  - alias: person_vacation
    hide_entity: true
    initial_state: true
    trigger:
      - platform: state
        entity_id: input_select.julias_status
        to: 'Away'
        for:
          hours: 24
      - platform: state
        entity_id: input_select.michaels_status
        to: 'Away'
        for:
          hours: 24
    action:
      - service: input_select.select_option
        data_template:
          entity_id: '{{ trigger.entity_id }}'
          option: 'Vacation'

################################################
## Device Tracker
################################################

# Device Tracking
# https://www.home-assistant.io/components/device_tracker.bluetooth_tracker/
#device_tracker:
#  - platform: bluetooth_tracker
#    new_device_defaults:
#      track_new_devices: false
#      hide_if_away: false

# https://www.home-assistant.io/components/device_tracker.owntracks/
device_tracker:
  - platform: owntracks
