################################################################
## Packages / Recorder
## https://home-assistant.io/components/recorder/
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'recorder'

################################################
## Recorder
################################################

recorder:
  purge_interval: 1
  purge_keep_days: 3
  exclude:
      domains:
        - camera
        - media_player
        - sun
        - weblink
      entities:
        - sensor.since_last_boot
        - sensor.date
        - sensor.time
