################################################################
## Package / Sensor Lights
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'sensor_lights'

    ################################################
    ## Automation
    ################################################

    automation.living_room_motion:
      <<: *customize
      friendly_name: "Living Room Motion"
      icon: mdi:walk

    automation.master_bedroom_motion:
      <<: *customize
      friendly_name: "Bedroom Motion"
      icon: mdi:walk

    automation.guest_closet_lighting:
      <<: *customize
      friendly_name: "Guest Closet Lighting"
      icon: mdi:lightbulb

    automation.guest_storage_lighting:
      <<: *customize
      friendly_name: "Guest Storage Lighting"
      icon: mdi:lightbulb

    automation.michael_closet_lighting:
      <<: *customize
      friendly_name: "Michael's Closet Lighting"
      icon: mdi:lightbulb
  
    automation.julia_closet_lighting:
      <<: *customize
      friendly_name: "Julia's Closet Lighting"
      icon: mdi:lightbulb

################################################
## Automation
################################################

automation:
  ################################################
  ## Motion Activated Lights
  ################################################

  - alias: living_room_motion
    initial_state: 'off'
    trigger:
      - platform: state
        entity_id: binary_sensor.living_room_motion_sensor
        from: 'off'
        to: 'on'
      - platform: state
        entity_id: binary_sensor.living_room_motion_sensor
        from: 'on'
        to: 'off'
        for: '00:25:00'
    action:
      - service: script.light_control
        data_template:
          entity_id: light.aeotec_zw099_smart_dimmer_6_level_2
          state: "{{ trigger.to_state.state }}"
          brightness: 178
          transition: 2
      - service: script.light_control
        data_template:
          entity_id: light.table_light
          state: "{{ trigger.to_state.state }}"
          brightness: 178
          effect: colorloop
#      - service: script.light_control
#        data_template:
#          entity_id: switch.aeotec_zw096_smart_switch_6_switch
#          state: "{{ trigger.to_state.state }}"

  - alias: master_bedroom_motion
    initial_state: 'off'
    trigger:
      - platform: state
        entity_id: binary_sensor.aeotec_zw100_multisensor_6_sensor
        from: 'off'
        to: 'on'
      - platform: state
        entity_id: binary_sensor.aeotec_zw100_multisensor_6_sensor
        from: 'on'
        to: 'off'
        for: '00:20:00'
    action:
      - service: script.light_control
        data_template:
          entity_id: light.dresser_lamp
          state: "{{ trigger.to_state.state }}"
          brightness: 178
          transition: 2
      - service: script.light_control
        data_template:
          entity_id: light.nightstand_lamp
          state: "{{ trigger.to_state.state }}"
          brightness: 178
          transition: 2

  ################################################
  ## Door Activated Lights
  ################################################

  - alias: guest_closet_lighting
    trigger:
      - platform: state
        entity_id: binary_sensor.fibaro_system_fgk10x_door_opening_sensor_sensor
    action:
      - service: script.light_control
        data_template:
          entity_id: light.linear_lb60z1_dimmable_led_light_bulb_level
          state: "{{ trigger.to_state.state }}"
          brightness: 255
          transition: 1

  - alias: guest_storage_lighting
    trigger:
      - platform: state
        entity_id: binary_sensor.guest_storage_door_contact
    action:
      - service: script.light_control
        data_template:
          entity_id: light.guest_room_storage
          state: "{{ trigger.to_state.state }}"
          brightness: 255
          transition: 1

  - alias: michael_closet_lighting
    trigger:
      - platform: state
        entity_id: binary_sensor.michaels_closet_door_contact
    action:
      - service: script.light_control
        data_template:
          entity_id: light.michaels_closet
          state: "{{ trigger.to_state.state }}"
          brightness: 255
          transition: 1

  - alias: julia_closet_lighting
    trigger:
      - platform: state
        entity_id: binary_sensor.julias_closet_door_contact
    action:
      - service: script.light_control
        data_template:
          entity_id: light.julias_closet
          state: "{{ trigger.to_state.state }}"
          brightness: 255
          transition: 1
