################################################################
## Packages / Sun
## https://home-assistant.io/components/sun/
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'sun'

    ################################################
    ## Sun
    ################################################

    sun.sun:
      <<: *customize
      friendly_name: "Sun"

################################################
## Sun
################################################

sun:
