################################################################
## Packages / Views
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'views'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Group
    ################################################

    group.automation:
      <<: *customize
      friendly_name: "Automation"
      icon: mdi:settings

    group.cameras:
      <<: *customize
      friendly_name: "Cameras"
      icon: mdi:camcorder

    group.home:
      <<: *customize
      friendly_name: "Home"
      icon: mdi:home

    group.household:
      <<: *customize
      friendly_name: "Household"
      icon: mdi:human-greeting

    group.media:
      <<: *customize
      friendly_name: "Media"
      icon: mdi:play-circle-outline

    group.network:
      <<: *customize
      friendly_name: "Network"
      icon: mdi:switch

    group.sensors:
      <<: *customize
      friendly_name: "Sensors"
      icon: mdi:access-point

    group.weather:
      <<: *customize
      friendly_name: "Weather"
      icon: mdi:weather-partlycloudy

################################################
## Group
################################################

group:
  home:
    view: yes
    entities:
      - group.basement
      - group.dining_room
      - group.entrance
      - group.garage
      - group.guest_bedroom
      - group.kitchen
      - group.laundry_room
      - group.living_room
      - group.master_bedroom
      - group.master_closets

#  household:
#    view: yes
#    entities:
#      - group.person_dale
#      - group.guests

  network:
    view: yes
    entities:
      - group.network_devices
      - group.web_power_switch
      - group.system
      - group.ups
      - group.utilities

  cameras:
    view: yes
    entities:
      - group.indoor_cameras

  sensors:
    view: yes
    entities:
      - group.weather
      - group.batteries
      - group.temperature
      - group.motion

  media:
    view: yes
    entities:
      - group.media_components
      - group.media_players

  automation:
    view: yes
    entities:
      - group.automation_override
      - group.all_automations
      - group.all_scripts

  weather:
    view: yes
    entities:
      - group.weather_general
      - group.weather_darksky
