################################################################
## Packages / WirelessTag
## https://www.home-assistant.io/components/wirelesstag/
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'wirelesstag'

    ################################################
    ## Group
    ################################################

    group.humidors:
      <<: *customize
      friendly_name: "Humidors"

    ################################################
    ## Plant
    ################################################

    plant.diamond_crown:
      <<: *customize
      friendly_name: 'Diamond Crown Humidor'

    plant.laundry_room:
      <<: *customize
      friendly_name: 'Desktop Humidor'

################################################
## Group
################################################

group:
  humidors:
    control: hidden
    entities:
      - sensor.wirelesstag_diamond_crown_humidor_humidity
      - sensor.wirelesstag_diamond_crown_humidor_light
      - sensor.wirelesstag_diamond_crown_humidor_temperature
      - sensor.wirelesstag_diamond_crown_humidor_battery
      - sensor.wirelesstag_laundry_room_humidity
      - sensor.wirelesstag_laundry_room_light
      - sensor.wirelesstag_laundry_room_temperature
      - sensor.wirelesstag_laundry_room_battery

################################################
## Sensors
## https://www.home-assistant.io/components/sensor.wirelesstag/
################################################

sensor:
  - platform: wirelesstag
    monitored_conditions:
      - temperature
      - humidity
      - light
  - platform: template
    sensors:
      wirelesstag_diamond_crown_humidor_battery:
        value_template: '{{ states.sensor.wirelesstag_diamond_crown_humidor_humidity.attributes.battery_level|float * 100 }}'
        unit_of_measurement: '%'
        icon_template: >-
          {% set battery_level = states('sensor.wirelesstag_diamond_crown_humidor_battery')|float * 100 %}
          {% if battery_level == 'unknown' %}
            mdi:battery-unknown
          {% else %}
            {% set battery_round = (battery_level|int / 10)|int * 10 %}
            {% if battery_round >= 100 %}
              mdi:battery
            {% elif battery_round > 0 %}
              mdi:battery-{{ battery_round }}
            {% else %}
              mdi:battery-alert
            {% endif %}
          {% endif %}

      wirelesstag_laundry_room_battery:
        value_template: '{{ states.sensor.wirelesstag_laundry_room_humidity.attributes.battery_level|float * 100 }}'
        unit_of_measurement: '%'
        icon_template: >-
          {% set battery_level = states('sensor.wirelesstag_laundry_room_battery')|float * 100 %}
          {% if battery_level == 'unknown' %}
            mdi:battery-unknown
          {% else %}
            {% set battery_round = (battery_level|int / 10)|int * 10 %}
            {% if battery_round >= 100 %}
              mdi:battery
            {% elif battery_round > 0 %}
              mdi:battery-{{ battery_round }}
            {% else %}
              mdi:battery-alert
            {% endif %}
          {% endif %}

################################################
## Plants
## https://www.home-assistant.io/components/plant/
################################################

plant:
  diamond_crown:
    sensors:
      moisture: sensor.wirelesstag_diamond_crown_humidor_humidity
      battery: sensor.wirelesstag_diamond_crown_humidor_battery
      temperature: sensor.wirelesstag_diamond_crown_humidor_temperature
      brightness: sensor.wirelesstag_diamond_crown_humidor_light
    min_moisture: 55
    max_moisture: 75
    min_battery: 10
    min_temperature: 50
    max_temperature: 85

  laundry_room:
    sensors:
      moisture: sensor.wirelesstag_laundry_room_humidity
      battery: sensor.wirelesstag_laundry_room_battery
      temperature: sensor.wirelesstag_laundry_room_temperature
      brightness: sensor.wirelesstag_laundry_room_light
    min_moisture: 55
    max_moisture: 75
    min_battery: 10
    min_temperature: 50
    max_temperature: 85

################################################
## WirelessTag
################################################

# WirelessTag
wirelesstag:
  username: !secret wirelesstag_username
  password: !secret wirelesstag_password
