################################################################
## Packages / WirelessTag
## https://www.home-assistant.io/components/wirelesstag/
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'wirelesstag'

    ################################################
    ## Plant
    ################################################

    plant.diamond_crown_humidor:
      <<: *customize
      friendly_name: 'Diamond Crown Humidor'

    plant.desktop_humidor:
      <<: *customize
      friendly_name: 'Desktop Humidor'

    ################################################
    ## Sensor
    ################################################
    sensor.wirelesstag_diamond_crown_humidor_battery:
      <<: *customize
      friendly_name: 'Diamond Crown Humidor Battery Level'
      device_class: battery

    sensor.wirelesstag_diamond_crown_humidor_humidity:
      <<: *customize
      friendly_name: 'Diamond Crown Humidor Humidity'
      device_class: humidity

    sensor.wirelesstag_diamond_crown_humidor_light:
      <<: *customize
      friendly_name: 'Diamond Crown Humidor Luminance'
      device_class: illuminance

    sensor.wirelesstag_diamond_crown_humidor_temperature:
      <<: *customize
      friendly_name: 'Diamond Crown Humidor Temperature'
      device_class: temperature

    sensor.wirelesstag_desktop_humidor_battery:
      <<: *customize
      friendly_name: 'Desktop Humidor Battery Level'
      device_class: battery

    sensor.wirelesstag_desktop_humidor_humidity:
      <<: *customize
      friendly_name: 'Desktop Humidor Humidity'
      device_class: humidity

    sensor.wirelesstag_desktop_humidor_light:
      <<: *customize
      friendly_name: 'Desktop Humidor Luminance'
      device_class: illuminance

    sensor.wirelesstag_desktop_humidor_temperature:
      <<: *customize
      friendly_name: 'Desktop Humidor Temperature'
      device_class: temperature

################################################
## Sensors
## https://www.home-assistant.io/components/sensor.wirelesstag/
################################################

sensor:
  - platform: wirelesstag
    monitored_conditions:
      - temperature
      - humidity
      - light

  - platform: template
    sensors:
      wirelesstag_diamond_crown_humidor_battery:
        value_template: '{{ (states.sensor.wirelesstag_diamond_crown_humidor_humidity.attributes.battery_level|float)|round }}'
        unit_of_measurement: '%'

      wirelesstag_desktop_humidor_battery:
        value_template: '{{ (states.sensor.wirelesstag_desktop_humidor_humidity.attributes.battery_level|float)|round }}'
        unit_of_measurement: '%'

################################################
## Plants
## https://www.home-assistant.io/components/plant/
################################################

plant:
  diamond_crown_humidor:
    sensors:
      moisture: sensor.wirelesstag_diamond_crown_humidor_humidity
      battery: sensor.wirelesstag_diamond_crown_humidor_battery
      temperature: sensor.wirelesstag_diamond_crown_humidor_temperature
      brightness: sensor.wirelesstag_diamond_crown_humidor_light
    min_moisture: 60
    max_moisture: 75
    min_battery: 10
    min_temperature: 60
    max_temperature: 80

  desktop_humidor:
    sensors:
      moisture: sensor.wirelesstag_desktop_humidor_humidity
      battery: sensor.wirelesstag_desktop_humidor_battery
      temperature: sensor.wirelesstag_desktop_humidor_temperature
      brightness: sensor.wirelesstag_desktop_humidor_light
    min_moisture: 60
    max_moisture: 75
    min_battery: 10
    min_temperature: 60
    max_temperature: 80

################################################
## WirelessTag
################################################

# WirelessTag
wirelesstag:
  username: !secret wirelesstag_username
  password: !secret wirelesstag_password
