################################################################
## Packages / Z-Wave
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'zwave'

      expose: &expose
        <<: *customize
        homebridge_hidden: false

    ################################################
    ## Lights
    ################################################

    light.aeotec_zw099_smart_dimmer_6_level_2:
      <<: *customize
      friendly_name: Floor Lamp
      icon: mdi:floor-lamp

    light.guest_bedroom_closet:
      <<: *customize
      friendly_name: Guest Closet Light
      icon: mdi:lightbulb

    light.garage_storage:
      <<: *customize
      friendly_name: Garage Storage Light
      icon: mdi:lightbulb

    light.dungeon:
      <<: *customize
      friendly_name: Dungeon Light
      icon: mdi:lightbulb

    ################################################
    ## Switches
    ################################################

    switch.aeotec_zw096_smart_switch_6_switch:
      <<: *customize
      friendly_name: Bookshelf Lamp
      icon: mdi:desk-lamp

    ################################################
    ## Z-Wave
    ################################################

    zwave.aeotec_zw090_zstick_gen5_us:
      friendly_name: "Z-Wave USB Hub"

    zwave.dungeon_light_bulb:
      friendly_name: "Dungeon Light Bulb"
      
    zwave.garage_storage_light_bulb:
      friendly_name: "Garage Storage Light Bulb"

    zwave.guest_bedroom_closet_door_contact:
      friendly_name: "Guest Bedroom Closet Door Contact"

    zwave.guest_bedroom_closet_light_bulb:
      friendly_name: "Guest Bedroom Closet Light Bulb"

    zwave.guest_bedroom_smoke_and_carbon_monoxide_detector:
      friendly_name: "Guest Bedroom Smoke and Carbon Monoxide Detector"

    zwave.guest_bedroom_storage_door_contact:
      friendly_name: "Guest Bedroom Storage Door Contact"

    zwave.julias_closet_door_contact:
      friendly_name: "Julia's Closet Door Contact"

    zwave.kitchen_range_extender:
      friendly_name: "Kitchen Range Extender"

    zwave.laundry_room_flood_sensor:
      friendly_name: "Laundry Room Flood Sensor"

    zwave.laundry_room_range_extender:
      friendly_name: "Laundry Room Range Extender"

    zwave.laundry_room_smoke_and_carbon_monoxide_detector:
      friendly_name: "Laundry Room Smoke and Carbon Monoxide Detector"

    zwave.living_room_motion_sensor:
      friendly_name: "Living Room Motion Sensor"

    zwave.master_bedroom_motion_sensor:
      friendly_name: "Master Bedroom Motion Sensor"

    zwave.master_bedroom_smoke_and_carbon_monoxide_detector:
      friendly_name: "Master Bedroom Smoke and Carbon Monoxide Detector"

    zwave.michaels_closet_door_contact:
      friendly_name: "Michael's Closet Door Contact"

  ################################################
  ## Customize Domain
  ################################################

  customize_domain:
    zwave:
      <<: *customize
      # hidden: true

################################################
## Z-Wave
################################################

zwave:
  usb_path: /dev/ttyACM0
  network_key: !secret zwave_network_key
  device_config: !include ../zwave_device_config.yaml
