################################################################
## Packages / Z-Wave
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'zwave'

      expose: &expose
        <<: *customize
        homebridge_hidden: false

    ################################################
    ## Binary Sensor
    ################################################

    binary_sensor.entrance_front_door_contact:
      <<: *customize
      friendly_name: Entrance Front Door
      device_class: door
      icon: mdi:door

    binary_sensor.guest_bedroom_closet_door_contact:
      <<: *customize
      friendly_name: Guest Bedroom Closet Door
      device_class: door
      icon: mdi:door

    binary_sensor.guest_bedroom_storage_door_contact:
      <<: *customize
      friendly_name: Guest Bedroom Storage Door
      device_class: door
      icon: mdi:door

    binary_sensor.julias_closet_door_contact:
      <<: *customize
      friendly_name: "Julia's Closet Door"
      device_class: door
      icon: mdi:door

    binary_sensor.living_room_motion_sensor:
      <<: *customize
      friendly_name: "Living Room Motion Sensor"
      icon: mdi:run

    binary_sensor.master_bedroom_motion_sensor:
      <<: *customize
      friendly_name: "Master Bedroom Motion Sensor"
      icon: mdi:run

    binary_sensor.michaels_closet_door_contact:
      <<: *customize
      friendly_name: "Michael's Closet Door"
      device_class: door
      icon: mdi:door

    ################################################
    ## Lights
    ################################################

    light.living_room_bookshelf_lamp:
      <<: *customize
      friendly_name: Bookshelf Lamp
      icon: mdi:desk-lamp

    light.living_room_floor_lamp:
      <<: *customize
      friendly_name: Floor Lamp
      icon: mdi:floor-lamp

    light.guest_bedroom_closet:
      <<: *customize
      friendly_name: Guest Closet Light
      icon: mdi:lightbulb

    light.garage_storage:
      <<: *customize
      friendly_name: Garage Storage Light
      icon: mdi:lightbulb

    light.dungeon:
      <<: *customize
      friendly_name: Dungeon Light
      icon: mdi:lightbulb

    ################################################
    ## Sensor
    ################################################

    sensor.guest_bedroom_smoke_and_carbon_monoxide_detector_alarm_level:
      <<: *customize
      friendly_name: Guest Bedroom Smoke Detector
      icon: mdi:smoke-detector

    sensor.guest_bedroom_storage_door_contact_burglar:
      <<: *customize
      friendly_name: "Guest Bedroom Closet Door Contact Burglar"
      icon: mdi:alarm-bell

    sensor.julias_closet_door_contact_burglar:
      <<: *customize
      friendly_name: "Julia's Closet Door Contact Burglar"
      icon: mdi:alarm-bell

    sensor.laundry_room_flood_sensor:
      <<: *customize
      friendly_name: "Laundry Room Flood Sensor"
      icon: mdi:water

    sensor.laundry_room_flood_sensor_burglar:
      <<: *customize
      friendly_name: "Laundry Room Flood Sensor Burglar"
      icon: mdi:alarm-bell

    sensor.laundry_room_flood_sensor_temperature:
      <<: *customize
      friendly_name: "Laundry Room Flood Sensor Temperature"
      icon: mdi:thermometer

    sensor.laundry_room_smoke_and_carbon_monoxide_detector_alarm_level:
      <<: *customize
      friendly_name: Laundry Room Smoke Detector
      icon: mdi:smoke-detector

    sensor.living_room_motion_sensor_burglar:
      <<: *customize
      friendly_name: Living Room Motion Sensor Burglar
      icon: mdi:alarm-bell

    sensor.living_room_motion_sensor_luminance:
      <<: *customize
      friendly_name: Living Room Motion Sensor Luminance
      icon: mdi:weather_sunny

    sensor.living_room_motion_sensor_seismic_intensity:
      <<: *customize
      friendly_name: Living Room Motion Sensor Seismic Intensity
      icon: mdi:vibrate

    sensor.living_room_motion_sensor_temperature:
      <<: *customize
      friendly_name: Living Room Motion Sensor Temperature
      icon: mdi:thermometer

    sensor.master_bedroom_motion_sensor_burglar:
      <<: *customize
      friendly_name: Master Bedroom Motion Sensor Burglar
      icon: mdi:alarm-bell

    sensor.master_bedroom_motion_sensor_luminance:
      <<: *customize
      friendly_name: Master Bedroom Motion Sensor Luminance
      icon: mdi:weather-sunny

    sensor.master_bedroom_motion_sensor_relative_humidity:
      <<: *customize
      friendly_name: Master Bedroom Motion Sensor Humidity
      icon: mdi:water-percent

    sensor.master_bedroom_motion_sensor_temperature:
      <<: *customize
      friendly_name: Master Bedroom Motion Sensor Temperature
      icon: mdi:thermometer

    sensor.master_bedroom_smoke_and_carbon_monoxide_detector_alarm_level:
      <<: *customize
      friendly_name: Master Bedroom Smoke Detector
      icon: mdi:smoke-detector

    sensor.michaels_closet_door_contact_burglar:
      <<: *customize
      friendly_name: "Michael's Closet Door Contact Burglar"
      icon: mdi:alarm-bell

    ################################################
    ## Switches
    ################################################

    switch.aeotec_zstick_disco_light:
      <<: *customize
      friendly_name: Z-Wave USB Hub Disco Light
      icon: mdi:chart-donut

    switch.basement_task_light:
      <<: *customize
      friendly_name: Basement Task Light
      icon: mdi:desk-lamp

    ################################################
    ## Z-Wave
    ################################################

    zwave.aeotec_zw090_zstick_gen5_us:
      friendly_name: "Z-Wave USB Hub"

    zwave.basement_task_light:
      friendly_name: "Basement Task Light"

    zwave.dungeon_light_bulb:
      friendly_name: "Dungeon Light Bulb"

    zwave.entrance_front_door_contact:
      friendly_name: "Entrance Front Door Contact"

    zwave.garage_door_opener:
      friendly_name: "Garage Door Opener"

    zwave.garage_storage_light_bulb:
      friendly_name: "Garage Storage Light Bulb"

    zwave.guest_bedroom_closet_door_contact:
      friendly_name: "Guest Bedroom Closet Door Contact"

    zwave.guest_bedroom_closet_light_bulb:
      friendly_name: "Guest Bedroom Closet Light Bulb"

    zwave.guest_bedroom_smoke_and_carbon_monoxide_detector:
      friendly_name: "Guest Bedroom Smoke and Carbon Monoxide Detector"

    zwave.guest_bedroom_storage_door_contact:
      friendly_name: "Guest Bedroom Storage Door Contact"

    zwave.julias_closet_door_contact:
      friendly_name: "Julia's Closet Door Contact"

    zwave.kitchen_range_extender:
      friendly_name: "Kitchen Range Extender"

    zwave.laundry_room_flood_sensor:
      friendly_name: "Laundry Room Flood Sensor"

    zwave.laundry_room_range_extender:
      friendly_name: "Laundry Room Range Extender"

    zwave.laundry_room_smoke_and_carbon_monoxide_detector:
      friendly_name: "Laundry Room Smoke and Carbon Monoxide Detector"

    zwave.living_room_bookshelf_lamp:
      friendly_name: "Living Room Bookshelf Lamp"

    zwave.living_room_floor_lamp:
      friendly_name: "Living Room Floor Lamp"

    zwave.living_room_motion_sensor:
      friendly_name: "Living Room Motion Sensor"

    zwave.master_bedroom_motion_sensor:
      friendly_name: "Master Bedroom Motion Sensor"

    zwave.master_bedroom_smoke_and_carbon_monoxide_detector:
      friendly_name: "Master Bedroom Smoke and Carbon Monoxide Detector"

    zwave.master_bedroom_remote:
      friendly_name: "Master Bedroom Remote"

    zwave.michaels_closet_door_contact:
      friendly_name: "Michael's Closet Door Contact"

  ################################################
  ## Customize Domain
  ################################################

  customize_domain:
    zwave:
      <<: *customize
      # hidden: true

################################################
## Switch
################################################

switch:
  - platform: command_line
    switches:
      aeotec_zstick_disco_light:
        friendly_name: 'Z-Wave USB Hub Disco Light'
        command_on: 'echo -e -n "\x01\x08\x00\xF2\x51\x01\x01\x05\x01\x50" > /dev/ttyACM0'
        command_off: 'echo -e -n "\x01\x08\x00\xF2\x51\x01\x00\x05\x01\x51" > /dev/ttyACM0'

################################################
## Z-Wave
################################################

zwave:
  usb_path: /dev/ttyACM0
  network_key: !secret zwave_network_key
  device_config: !include ../zwave_device_config.yaml
