################################################################
## Packages / Z-Wave Remotes
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'zwave_remotes'

      expose: &expose
        <<: *customize
        homebridge_hidden: false

    ################################################
    ## Automation
    ################################################

    automation.keyfob_button_pressed:
      <<: *customize
      friendly_name: "Keyfob Button Pressed"
      hidden: true

################################################
## Automation
################################################

automation:
  - alias: "Circle Button Tap Nightstand Light On"
    trigger:
      - platform: event
        event_type: zwave.scene_activated
        event_data:
          entity_id: zwave.fibaro_system_fgkf601_keyfob
          scene_id: 2
          scene_data: 7680
    action:
      - service: script.light_control
        data_template:
          entity_id: light.nightstand_lamp
          state: 'on'
          brightness: 178
          transition: 2
  - alias: "Square Button Tap Nightstand Light Off"
    trigger:
      - platform: event
        event_type: zwave.scene_activated
        event_data:
          entity_id: zwave.fibaro_system_fgkf601_keyfob
          scene_id: 1
          scene_data: 7680
    action:
      - service: script.light_control
        data_template:
          entity_id: light.nightstand_lamp
          state: 'off'
          brightness: 178
          transition: 2


  - alias: "Tringle Button Tap Dresser Light On"
    trigger:
      - platform: event
        event_type: zwave.scene_activated
        event_data:
          entity_id: zwave.fibaro_system_fgkf601_keyfob
          scene_id: 4
          scene_data: 7680
    action:
      - service: script.light_control
        data_template:
          entity_id: light.dresser_lamp
          state: 'on'
          brightness: 178
          transition: 2
  - alias: "X Button Tap Dresser Light Off"
    trigger:
      - platform: event
        event_type: zwave.scene_activated
        event_data:
          entity_id: zwave.fibaro_system_fgkf601_keyfob
          scene_id: 3
          scene_data: 7680
    action:
      - service: script.light_control
        data_template:
          entity_id: light.dresser_lamp
          state: 'off'
          brightness: 178
          transition: 2

  ################################################
  ## Minus Button
  ################################################

  - alias: "Minus Button Hold Night Mode On"
    trigger:
      - platform: event
        event_type: zwave.scene_activated
        event_data:
          entity_id: zwave.fibaro_system_fgkf601_keyfob
          scene_id: 5
          scene_data: 7800
    action:
      - service: script.good_night

  ################################################
  ## Plus Button
  ################################################

  - alias: "Plus Button Hold Bedroom Motion Off"
    trigger:
      - platform: event
        event_type: zwave.scene_activated
        event_data:
          entity_id: zwave.fibaro_system_fgkf601_keyfob
          scene_id: 6
          scene_data: 7800
    action:
      - service: automation.turn_off
        data:
          entity_id:
            - automation.master_bedroom_motion

  - alias: "Plus Button Tap Bedroom Motion On"
    trigger:
      - platform: event
        event_type: zwave.scene_activated
        event_data:
          entity_id: zwave.fibaro_system_fgkf601_keyfob
          scene_id: 6
          scene_data: 7680
    action:
      - service: automation.turn_on
        data:
          entity_id:
            - automation.master_bedroom_motion
